### ISSUE TITLE
Unable to upload CSV/JSONL timeline

### ISSUE THREAD

**Issue by oodeagleoo** [google/timesketch#1072]
I'm using `tsctl import` to upload a timeline from timeliner (volatility) containing all mandatory fields and one extra details field. However, timesketch prints and error message and shows the following error details for the previously uploaded timeline. Furthermore, it doesn't matter, if I upload the timeline as .csv or .jsonl.

**Error details:**
`[2020-01-01 15:03:27,913: ERROR/ForkPoolWorker-2] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/timesketch-20190609-py2.7.egg/timesketch/lib/tasks.py", line 466, in run_csv_jsonl
    es.create_index(index_name=index_name, doc_type=event_type)
  File "/usr/local/lib/python2.7/dist-packages/timesketch-20190609-py2.7.egg/timesketch/lib/datastores/elastic.py", line 490, in create_index
    index=index_name, body={'mappings': _document_mapping})
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 104, in create
    "PUT", _make_path(index), params=params, body=body
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
RequestError: RequestError(400, u'mapper_parsing_exception', u'Root mapping definition has unsupported parameters:  [generic_event : {properties={timesketch_label={type=nested}}}]')`

**Comment by berggren** [comment]
Hi, this looks like an ES issue. What version of ES are you running?

**Comment by oodeagleoo** [comment]
I'm running ES 7.5.1 amd64.

**OS:** Tsurugi Linux 2019.2

**Kernel:** Linux thinkpad 5.4.2-050402-tsurugi # 1 SMP Tue Dec 10 21:18:57 CET 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kiddinn** [comment]
is this still an issue?

have you tried importing the file outside the actual server and use the timesketch importer?

```
pip install timesketch-import-client
timesketch_importer.py --sketch_id <ID> <FILE>
```

**Comment by berggren** [comment]
We have better ES7 support now, and this should have been fixed.
@oodeagleoo please reopen if this is still an issue.
