### ISSUE TITLE
Issue importing timeline via tsctl import

### ISSUE THREAD

**Issue by wajihyassine** [google/timesketch#1093]
Hello, in attempting to import a timeline generated from psort.py via the timesketch command line tool `tsctl`, I'm running into a NoneType error as shown in the traceback below. I tried this with the .plaso file format as well. I confirmed that the file does have readable data in it. Note that I am using the docker version of timesketch.
```
tsctl import -f <timeline>.jsonl -u <username>
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: a bytes-like object is required, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/timesketch/tsctl.py", line 474, in main
    shell_manager.run()
  File "/usr/local/lib/python3.6/dist-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/timesketch/tsctl.py", line 389, in run
    timeline_name = codecs.decode(timeline_name, 'utf-8')
TypeError: <timesketch.tsctl.ImportTimeline object at 0x7f2648558080>: decoding with 'utf-8' codec failed (TypeError: a bytes-like object is required, not 'NoneType')
```

**Comment by kiddinn** [comment]
I'll take a look
