### ISSUE TITLE
Setup.py fails to build

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#1094]
Using:
```
$ pip --version
pip 20.0.2 from ....
```

I can no longer use setup.py to build the tool:

```
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    from pip._internal.download import PipSession
ModuleNotFoundError: No module named 'pip._internal.download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    from pip.download import PipSession
ModuleNotFoundError: No module named 'pip.download'

```

Looking at the pypi documentation I see: https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program

More specifically:
```
pip is a command line program. While it is implemented in Python, and so is available from your Python code via import pip, you must not use pip’s internal APIs in this way
```

The supported way of using it is:
```
subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'my_package'])
```

**Comment by joachimmetz** [comment]
Related/Duplicate https://github.com/google/timesketch/issues/1190

**Comment by jaegeral** [comment]
Is this still an issue?

**Comment by jaegeral** [comment]
https://github.com/google/timesketch/issues/1190 dealt already with it, closing this one out.
