### ISSUE TITLE
Timeout inserting timeline

### ISSUE THREAD

**Issue by Onager** [google/timesketch#121]
Traceback only for now
```
[INFO] 118000 events added
[INFO] Starting new HTTP connection (2): 127.0.0.1
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 646, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 641, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 593, in ProcessStorage
    self._ProcessStorage()
  File "/usr/bin/psort.py", line 236, in _ProcessStorage
    time_slice=time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 422, in ProcessStorage
    analysis_queues=event_queue_producers)
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 241, in __exit__
    self.End()
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 237, in End
    self._output_module.Close()
  File "/usr/lib/python2.7/dist-packages/plaso/output/timesketch_out.py", line 132, in Close
    self._FlushEventsToElasticsearch()
  File "/usr/lib/python2.7/dist-packages/plaso/output/timesketch_out.py", line 121, in _FlushEventsToElasticsearch
    index=self._index_name, doc_type=self._doc_type, body=self._events)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 774, in bulk
    doc_type, '_bulk'), params=params, body=self._bulk_body(body))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 86, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'127.0.0.1', port=9200): Read timed out. (read timeout=10))
```

**Comment by Onager** [comment]
This might actually belong in Plaso, not timesketch

**Comment by berggren** [comment]
Closing issue, because this is not timesketch, but plaso issue.

**Comment by wjohnsonsled** [comment]
Which issue in plaso?  Any fixes or workarounds?  I am getting the exact same thing today..

**Comment by berggren** [comment]
+ @Onager
