### ISSUE TITLE
import timesketch fails due to missing chain_plugins

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#1210]
While testing the 20200507 dpkg build in GIFT PPA dev

```
>>> import timesketch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/dist-packages/timesketch/__init__.py", line 30, in <module>
    from timesketch.api.v1.routes import API_ROUTES as V1_API_ROUTES
  File "/usr/lib/python3.6/dist-packages/timesketch/api/v1/routes.py", line 18, in <module>
    from .resources import AggregationGroupResource
  File "/usr/lib/python3.6/dist-packages/timesketch/api/v1/resources.py", line 58, in <module>
    from timesketch.lib.analyzers import manager as analyzer_manager
  File "/usr/lib/python3.6/dist-packages/timesketch/lib/analyzers/__init__.py", line 20, in <module>
    from timesketch.lib.analyzers import chain
  File "/usr/lib/python3.6/dist-packages/timesketch/lib/analyzers/chain.py", line 10, in <module>
    from timesketch.lib.analyzers import chain_plugins  # pylint: disable=unused-import
ImportError: cannot import name 'chain_plugins'

>>> import timesketch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/dist-packages/timesketch/__init__.py", line 30, in <module>
    from timesketch.api.v1.routes import API_ROUTES as V1_API_ROUTES
  File "/usr/lib/python3.6/dist-packages/timesketch/api/v1/routes.py", line 18, in <module>
    from .resources import AggregationGroupResource
  File "/usr/lib/python3.6/dist-packages/timesketch/api/v1/resources.py", line 58, in <module>
    from timesketch.lib.analyzers import manager as analyzer_manager
  File "/usr/lib/python3.6/dist-packages/timesketch/lib/analyzers/__init__.py", line 20, in <module>
    from timesketch.lib.analyzers import chain
  File "/usr/lib/python3.6/dist-packages/timesketch/lib/analyzers/chain.py", line 11, in <module>
    from timesketch.lib.analyzers.chain_plugins import manager as chain_manager
ModuleNotFoundError: No module named 'timesketch.lib.analyzers.chain_plugins'
```

**Comment by joachimmetz** [comment]
Removing these 2 imports (and some other tweaks) allow `import timesketch` to succeed

**Comment by joachimmetz** [comment]
Looks like these files are not included in the package https://github.com/google/timesketch/blob/master/config/dpkg/python3-timesketch.install

**Comment by joachimmetz** [comment]
Added fix to https://github.com/google/timesketch/pull/1212
