### ISSUE TITLE
dpkg control missing python3-tabulate

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#1211]
While testing the 20200507 dpkg build in GIFT PPA dev

```
>>> import timesketch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/dist-packages/timesketch/__init__.py", line 30, in <module>
    from timesketch.api.v1.routes import API_ROUTES as V1_API_ROUTES
  File "/usr/lib/python3.6/dist-packages/timesketch/api/v1/routes.py", line 18, in <module>
    from .resources import AggregationGroupResource
  File "/usr/lib/python3.6/dist-packages/timesketch/api/v1/resources.py", line 85, in <module>
    from timesketch.lib.stories import api_fetcher as story_api_fetcher
  File "/usr/lib/python3.6/dist-packages/timesketch/lib/stories/__init__.py", line 17, in <module>
    from timesketch.lib.stories import markdown
  File "/usr/lib/python3.6/dist-packages/timesketch/lib/stories/markdown.py", line 18, in <module>
    import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

python3-tabulate needs to be added to https://github.com/google/timesketch/blob/master/config/dpkg/control

**Comment by joachimmetz** [comment]
https://github.com/google/timesketch/pull/1212

**Comment by joachimmetz** [comment]
Changes have been merged
