### ISSUE TITLE
Informational: update minimum version of Flask-Testing to 0.8.0

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#1238]
Mainly for context why I'll bump the minimum version of Flask-Testing to 0.8.0. With Flask-Testing to 0.7.1 and Werkzeug 1.0.1, the CI tests error with:

```
======================================================================
ERROR: Failure: ImportError (cannot import name 'cached_property' from 'werkzeug' (/usr/lib/python3/dist-packages/werkzeug/__init__.py))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/timesketch/timesketch/api/v1/resources_test.py", line 24, in <module>
    from timesketch.lib.testlib import BaseTest
  File "/timesketch/timesketch/lib/testlib.py", line 22, in <module>
    from flask_testing import TestCase
  File "/usr/lib/python3/dist-packages/flask_testing/__init__.py", line 13, in <module>
    from .utils import TestCase, LiveServerTestCase
  File "/usr/lib/python3/dist-packages/flask_testing/utils.py", line 35, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/lib/python3/dist-packages/werkzeug/__init__.py)
-------------------- >> begin captured logging << --------------------
```

**Comment by joachimmetz** [comment]
Then again the PyPI requirementd is pinned to Werkzeug 0.16

**Comment by joachimmetz** [comment]
Not an issue closing
