### ISSUE TITLE
Installation: `sudo pip3 install timesketch` fails

### ISSUE THREAD

**Issue by irvinhomem** [google/timesketch#1244]
Following the Installation instructions fails with the following error (on a clean Ubuntu Server 20.04 installation ):

```
Collecting timesketch
  Using cached timesketch-20200507.tar.gz (8.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yng81v4j/timesketch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yng81v4j/timesketch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-yng81v4j/timesketch/pip-egg-info
         cwd: /tmp/pip-install-yng81v4j/timesketch/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-yng81v4j/timesketch/setup.py", line 32, in <module>
        from pip._internal.download import PipSession
    ModuleNotFoundError: No module named 'pip._internal.download'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yng81v4j/timesketch/setup.py", line 35, in <module>
        from pip.download import PipSession
    ModuleNotFoundError: No module named 'pip.download'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Seems like some bug related to an older version of `pip` ...

**Comment by joachimmetz** [comment]
Related/Duplicate https://github.com/google/timesketch/issues/1190

**Comment by jaegeral** [comment]
https://github.com/google/timesketch/issues/1190 is already closed, so closing this one out as well.
