### ISSUE TITLE
`add_index` option no longer functions

### ISSUE THREAD

**Issue by cshanahan** [google/timesketch#1270]
**TS Version**
Using Timesketch from Git master; installed on 2020-06-10
Using Plaso 20200430 from GIFT PPA

**STEPS TO REPRODUCE**
- Use psort from Plaso to ingest a plaso DB file into Elasticsearch
- Run `tsctl` with `add_index` option to associate an existing index with Timesketch
    - `tsctl add_index --index <my elastic index name> --name <name in timesketch> --user <my timesketch username>`
- `tsctl add_index` command completes without error
- Run `tsctl run_server` log in to the app and create a new Sketch
- From the Sketch UI the new index is not available as an option to add to the Sketch (it doesn't appear in the UI)

The index in Elasticsearch is fine. I can explore the index using other apps, including Kibana.

If it helps, Elasticsearch is pinned to v7.5.1

**Comment by kiddinn** [comment]
in this case, have you tried to use the timesketch importer? that can be used from every machine that can reach teh web interface of TS.

**Comment by cshanahan** [comment]
> in this case, have you tried to use the timesketch importer? that can be used from every machine that can reach teh web interface of TS.

I have never had much success with the import function. I almost always work with Plaso DB files, not JSONL or CSV.

Can you provide an example command using _import_ ?

For example, I just performed a test using the same Plaso DB file. I copied the Plaso DB file to the Timesketch server and ran the following (sanitized) command:

- tsctl import -h
usage: tsctl import [-?] --file FILE_PATH [--sketch_id SKETCH_ID] [--username USERNAME] [--timeline_name TIMELINE_NAME]

- tsctl import --file MY_TIMELINE.plaso --sketch_id importtest --username MY_USERNAME --timeline_name MY_TIMELINE                

And this was the traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "importtest"
LINE 3: WHERE sketch.id = 'importtest'
                          ^
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/timesketch/tsctl.py", line 517, in main
    shell_manager.run()
  File "/usr/local/lib/python3.8/dist-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.8/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/tsctl.py", line 418, in run
    sketch = Sketch.query.get_with_acl(sketch_id, user=user)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/models/__init__.py", line 81, in get_with_acl
    result_obj = self.get(model_id)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 982, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 1094, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/loading.py", line 284, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3325, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "importtest"
LINE 3: WHERE sketch.id = 'importtest'
                          ^
[SQL: SELECT sketch.id AS sketch_id, sketch.created_at AS sketch_created_at, sketch.updated_at AS sketch_updated_at, sketch.name AS sketch_name, sketch.description AS sketch_description, sketch.user_id AS sketch_user_id 
FROM sketch 
WHERE sketch.id = %(param_1)s]
[parameters: {'param_1': 'importtest'}]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by kiddinn** [comment]
OK, thank you for the traceback, I know now where to look and can fix this.

In the meantime I encourage you to try the importer... you'll need to install it first `pip install timesketch_import_client` and then you can simply run:
```
timesketch_importer.py --sketch_id ID FILENAME.plaso
```

The first time you connect you'll be asked questions regarding auth, and location of server, etc. and then after that, it'll be remembered.

**Comment by kiddinn** [comment]
I noticed you ran the command as:
```
$ tsctl import --file MY_TIMELINE.plaso --sketch_id importtest --username MY_USERNAME --timeline_name MY_TIMELINE
```

The `sketch_id` parameter takes in an integer, not a name of the sketch. Can you run this with the `--sketch_id SKETCH_ID` that is using the ID or sketch number instead of the sketch's name.
