### ISSUE TITLE
Version conflict with jsonschema between pymisp and altair

### ISSUE THREAD

**Issue by CluelessAtCoding** [google/timesketch#1271]
Working through the Manual Installation instructions on Ubuntu 18.04 Server and the process fails at: 

Add the first user:
$ tsctl add_user -u <username>

With the following Error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 2.6.0 (/usr/lib/python3/dist-packages), Requirement.parse('jsonschema<4.0.0,>=3.2.0'), {'pymisp'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3261, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 2.6.0 (/usr/lib/python3/dist-packages), Requirement.parse('jsonschema<4.0.0,>=3.2.0'), {'pymisp'})

Running "sudo pip3 install jsonschema==3.2.0" seems to resolve the issue.

**Comment by joachimmetz** [comment]
Looks like pymisp is installing jsonschema with out version requirements (for some reason both as a runtime requirement and for testing https://github.com/MISP/PyMISP/blob/main/setup.py#L41). 

jsonschema is also used by altair https://github.com/google/timesketch/blob/master/requirements.txt#L2

This is not much of a Timesketch issue. I recommend using virtualenv or Docker to isolate different tools that have conflicting dependency requirements, especially when using pip

**Comment by berggren** [comment]
I agree: This is not much of a Timesketch issue per se. Closing out.
