### ISSUE TITLE
sigma_tagger.py UnicodeDecodeError and other exceptions

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1305]
Some sigma rules from the sigma upstream project are causing Exceptions like:

```Traceback (most recent call last): File "/usr/local/src/timesketch/timesketch/lib/analyzers/interface.py", line 804, in run_wrapper result = self.run() File "/usr/local/src/timesketch/timesketch/lib/analyzers/sigma_tagger.py", line 105, in run rule_file_content = rule_file.read() File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode return codecs.ascii_decode(input, self.errors)[0] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 214: ordinal not in range(128)```

IN the past, there was an except block to catch all of them and not cause it to stop:
https://github.com/jaegeral/timesketch/blob/c926b3889b0eafdc6a060a51c05d8446a766cc3d/timesketch/lib/analyzers/sigma_tagger.py#L114

This was however not really elegant and is problematic as it would only occur for analysts running analyzers, which not all have access to the logs of Timesketch, so they would not know why it did not work.

Three possible ways to address that:
a) re-introduce the broad except
b) write a small tool that checks all rules that can be used by an admin when rules are added
c) fix the problem upstream

or: do nothing.

**Comment by jaegeral** [comment]
If we want to go for b) @kiddinn would you want such a tool similar to: https://github.com/google/timesketch/blob/master/test_tools/analyzer_run.py but without the need to provide events?

**Comment by jaegeral** [comment]
This is basically addressed in the PR: https://github.com/google/timesketch/pull/1307 and is still WIP.

**Comment by jaegeral** [comment]
This will be fixed once https://github.com/google/timesketch/pull/1456 is in and the analyzer code also has been refactored to use the same lib.

The lib will do a few exception handlings and basically ignore those rules, other then this there is https://github.com/google/timesketch/blob/master/test_tools/sigma_verify_rules.py.

**Comment by jaegeral** [comment]
OK it is safe to close out this issue, as the except statements provide enought safety to not crash the analyzer, investigating why certain rules do not work need to be done.
