### ISSUE TITLE
Error when importing PLASO file 

### ISSUE THREAD

**Issue by Silentcartographer** [google/timesketch#1402]
I am getting the following error when importing a PLASO file via the web interface on a dev docker instance, pulled today:
2020-10-08 21:28:17,685 [INFO] (MainProcess) PID:148 <data_location> Determined data location: /usr/share/plaso
2020-10-08 21:28:18,195 [INFO] (MainProcess) PID:148 <timesketch_out> Timeline name: output
2020-10-08 21:28:18,196 [INFO] (MainProcess) PID:148 <timesketch_out> Owner of the timeline: None
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 643, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_string)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 427, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 446, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 275, in _ConvertDictToObject
    'supported.').format(attribute_name))
ValueError: Event data attribute value: strings_parsed of type dict is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 99, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 76, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 598, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 1045, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 527, in _ExportEvents
    event_data_identifier)
  File "/usr/lib/python3/dist-packages/plaso/storage/file_interface.py", line 309, in GetEventDataByIdentifier
    return self._storage_file.GetEventDataByIdentifier(identifier)
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 905, in GetEventDataByIdentifier
    self._CONTAINER_TYPE_EVENT_DATA, identifier.row_identifier - 1)
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 337, in _GetAttributeContainerByIndex
    container_type, serialized_data)
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 650, in _DeserializeAttributeContainer
    raise IOError('Unable to read serialized data: {0!s}'.format(exception))
OSError: Unable to read serialized data: Event data attribute value: strings_parsed of type dict is not supported.

The PLASO was generated using version log2timeline version 20200121

**Comment by joachimmetz** [comment]
Can you update your Plaso version, it is older than 6 months and a lot of things changes in 6 months.

**Comment by jaegeral** [comment]
Closing this one out, as there was no update.
