### ISSUE TITLE
Sigma config TypeError not NoneType

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1439]
```
805588172-[2020-10-29 14:26:09,183] celery.app.trace/ERROR Task timesketch.lib.tasks.run_sketch_analyzer[aaaaa] raised unexpected: TypeError('expected str, bytes or os.PathLike object, not NoneType',)
805588394-Traceback (most recent call last):
805588429-  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 385, in trace_task
805588522-    R = retval = fun(*args, **kwargs)
805588560-  File "/usr/local/lib/python3.6/dist-packages/timesketch/app.py", line 198, in __call__
805588649-    return TaskBase.__call__(self, *args, **kwargs)
805588701-  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 650, in __protected_call__
805588802-    return self.run(*args, **kwargs)
805588839-  File "/usr/local/lib/python3.6/dist-packages/timesketch/lib/tasks.py", line 459, in run_sketch_analyzer
805588945-    sketch_id=sketch_id, index_name=index_name, **kwargs)
805589003:  File "/usr/local/lib/python3.6/dist-packages/timesketch/lib/analyzers/sigma_tagger.py", line 44, in __init__
805589114:    with open(sigma_config_path, 'r') as sigma_config_file:
805589174-TypeError: expected str, bytes or os.PathLike object, not NoneType
```

If ```sigma_config_path```is none it will fail, so create a check if the ```/etc/timesketch/sigma_config.yaml``` can not be read. This is mostly the case for manual installations, not docker ones that is why it does not occur if docker instance is used.

The end result will be just a yellow traffic light forever.

**Comment by jaegeral** [comment]
This will be fixed once https://github.com/google/timesketch/pull/1456 is in and the analyzer code also has been refactored to use the same lib.

**Comment by jaegeral** [comment]
OK this is now also fixed with the new https://github.com/google/timesketch/blob/master/timesketch/lib/sigma_util.py
