### ISSUE TITLE
Large plaso files upload failure 

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1659]
**Describe the bug**
Upload fails using timesketch_import_client when uploading a large plaso file. 

**To Reproduce**
1. upload to timesketch using timesketch_import_client a plaso file larger than (3gb) 
preumblay the upload will fail when the file size exceeds 999999999 bytes

**Expected behavior**
The plaso file should be correctly uploaded and then processing and indexing of the file should start 

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Ubuntu 20.04.2 LTS
 - Browser : Firefox  
 - Version: 86.0

**Additional context**
- Timesketch docker version:latest
- wsgi_error.log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/upload.py", line 415, in post
    return self._upload_file(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/upload.py", line 355, in _upload_file
    return self._upload_and_index(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/upload.py", line 206, in _upload_and_index
    db_session.commit()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range

[SQL: INSERT INTO datasource (created_at, updated_at, timeline_id, user_id, provider, context, file_on_disk, file_size, original_filename, data_label) VALUES (now(), now(), %(timeline_id)s, %(user_id)s, %(provider)s, %(context)s, %(file_on_disk)s, %(file_size)s, %(original_filename)s, %(data_label)s) RETURNING datasource.id]
[parameters: {'timeline_id': 8, 'user_id': 1, 'provider': 'Imported via the importer library.', 'context': 'N/A', 'file_on_disk': '/usr/share/timesketch/upload/7894e7b9a77d43c3bca8511561395f84', 'file_size': 3203993600, 'original_filename': '*****', 'data_label': 'plaso'}]
```

**Comment by kiddinn** [comment]
if you look into the actual error message, it does not seem to be related to the size of the plaso file, this is a DB error while trying to store the information about the file into the SQL database,...

```
sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range

[SQL: INSERT INTO datasource (created_at, updated_at, timeline_id, user_id, provider, context, file_on_disk, file_size, original_filename, data_label) VALUES (now(), now(), %(timeline_id)s, %(user_id)s, %(provider)s, %(context)s, %(file_on_disk)s, %(file_size)s, %(original_filename)s, %(data_label)s) RETURNING datasource.id]
[parameters: {'timeline_id': 8, 'user_id': 1, 'provider': 'Imported via the importer library.', 'context': 'N/A', 'file_on_disk': '/usr/share/timesketch/upload/7894e7b9a77d43c3bca8511561395f84', 'file_size': 3203993600, 'original_filename': '*****', 'data_label': 'plaso'}]
```

And this is the data source table...we'll need to take a closer look at this, and fix the DB model or the DB code here.

**Comment by kiddinn** [comment]
ok, so according to: https://www.postgresql.org/docs/9.1/datatype-numeric.html

we are using an Integer value for the file size in the data source model, which means from: `-2147483648 to +2147483647`

probably it would be better to designate this field as either a bigint, or as a decimal.

**Comment by kiddinn** [comment]
that would require a change in the db model, or we can simply change the intepretation and instead of having file size as bytes, we can move that to represent MBs, which would change quite a bit, since this is really putting an upper limit of file sizes to about 2 Gb....

**Comment by kiddinn** [comment]
manually testing on the dB to confirm:

```
timesketch=# update datasource set file_size=2147483650 where id=2;
ERROR:  integer out of range
```

**Comment by kiddinn** [comment]
the solution here is to either change the DB model or to change how we store the file size on disk.

Let's move to changing the DB model to use a bigint instead of an int.

**Comment by kiddinn** [comment]
Fix will be applied in #1662

**Comment by kiddinn** [comment]
can you upgrade you installation?

you'll need to apply the db schema, you'll need to run (inside the ts container, inside teh /usr/local/src/timesketch/timesketch/ folder the following command:

```shell
tsctl db upgrade
```

and then can you try uploading the file again, to see if this has been fixed.

If this is still an issue, can you re-open the bug.

**Comment by rushattac** [comment]
the folder /usr/local/src/timesketch/timesketch doesn't exist in the docker container and i get the following message after creating the folder:
```
2021-03-03 14:09:50 ERROR    Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
```
creating the migrations folder generates the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/timesketch/tsctl.py", line 465, in main
    shell_manager.run()
  File "/usr/local/lib/python3.8/dist-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.8/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 412, in stamp
    command.stamp(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 579, in stamp
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 102, in load_python_file
    raise ImportError("Can't find Python file %s" % path)
ImportError: Can't find Python file migrations/env.py

```

**Comment by kiddinn** [comment]
What docker config are you using?

+ If you use **dev** (see https://github.com/google/timesketch/blob/master/docker/dev/docker-compose.yml#L30 then this folder should exist and maps to the source code of TS)
+ If you use the **release** OTOH then you need to connect to timesketch-web container and fetch the source first

```shell
sudo docker exec -it ..... /bin/bash
# cd /tmp/
# git clone https://github.com/google/timesketch.git
# cd timesketch/timesketch
``

and then run the DB commands

**Comment by kiddinn** [comment]
see https://github.com/google/timesketch/blob/master/docs/Upgrading.md#upgrade-the-database-schema

**Comment by rushattac** [comment]
when trying to apply the above procedure i get the following error:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./tsctl.py", line 469, in <module>
    main()
  File "./tsctl.py", line 465, in main
    shell_manager.run()
  File "/usr/local/lib/python3.8/dist-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.8/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 91, in <module>
    run_migrations_online()
  File "migrations/env.py", line 84, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/timesketch/timesketch/migrations/versions/be32626451fb_.py", line 22, in upgrade
    op.add_column('searchindex_accesscontrolentry', sa.Column('group_id', sa.Integer(), nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/ops.py", line 1906, in add_column
    return operations.invoke(op)
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/toimpl.py", line 131, in add_column
    operations.impl.add_column(table_name, column, schema=schema)
  File "/usr/local/lib/python3.8/dist-packages/alembic/ddl/impl.py", line 231, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.8/dist-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1039, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateColumn) column "group_id" of relation "searchindex_accesscontrolentry" already exists

[SQL: ALTER TABLE searchindex_accesscontrolentry ADD COLUMN group_id INTEGER]
```

**Comment by kiddinn** [comment]
ok, so the upgrade of the DB worked, but does the large file upload now work?

**Comment by rushattac** [comment]
no the upload didn't work shouldn't the type be ```sa.bigint``` instead of ```type_=sa.BigInteger```?

**Comment by kiddinn** [comment]
same error that you got on the upload?

can you confirm one thing ,if you enter the DB and type

```
\d datasource
```

you should get something like this:

```
timesketch=# \d datasource
                                            Table "public.datasource"
      Column       |            Type             | Collation | Nullable |                Default                 
-------------------+-----------------------------+-----------+----------+----------------------------------------
 id                | integer                     |           | not null | nextval('datasource_id_seq'::regclass)
 created_at        | timestamp without time zone |           |          | 
 updated_at        | timestamp without time zone |           |          | 
 timeline_id       | integer                     |           |          | 
 user_id           | integer                     |           |          | 
 provider          | text                        |           |          | 
 context           | text                        |           |          | 
 file_on_disk      | text                        |           |          | 
 file_size         | bigint                      |           |          | 
 original_filename | text                        |           |          | 
 data_label        | text                        |           |          | 
Indexes:
    "datasource_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "datasource_timeline_id_fkey" FOREIGN KEY (timeline_id) REFERENCES timeline(id)
    "datasource_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id)
Referenced by:
    TABLE "datasource_comment" CONSTRAINT "datasource_comment_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES datasource(id)
    TABLE "datasource_label" CONSTRAINT "datasource_label_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES datasource(id)
    TABLE "datasource_status" CONSTRAINT "datasource_status_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES datasource(id)

```

is this not how it looks like for you?

And `sa.BigInteger` is SQLAlchemy's way of defining `bigint` in the DB

**Comment by rushattac** [comment]
changing the revsion file to have the below line worked:
```
op.alter_column('datasource', 'file_size', type_=sa.BigInteger,postgresql_using='file_size::bigint')
```

**Comment by rushattac** [comment]
> bigint

the database showed the data_type for the file_size column as integer

**Comment by kiddinn** [comment]
that's strange, the other revision file worked fine for me... we'll need to document this for others if it doesn't work in other cases too...

but does the table now show bigint?

and can you then retry the upload?

**Comment by rushattac** [comment]
first i manually editing the database and changed the type to bigint then reverted it and tested with the operation mentioned above which successfully changed the datatype. 
the current type is bigint i will reuplaod the files and update you with the progress

**Comment by rushattac** [comment]
I've uploaded the file again and it works great

**Comment by kiddinn** [comment]
Great, then this is fixed, good to know, thanks for helping me out debugging this
