### ISSUE TITLE
Cannot upgrade from 20200507 to 20210224

### ISSUE THREAD

**Issue by Kamforka** [google/timesketch#1661]
**Describe the bug**
Trying to upgrade from version 20200507 to 20210224 but `tsctl db upgrade` fails to execute properly.

**Expected behavior**
Expect `tsctl db upgrade` to upgrade the database schema without errors.

**Output**
```python
tsctl db upgrade
Warning, EMAIL_USER_WHITELIST has been deprecated. Please update timesketch.conf.INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> be32626451fb, Add ACL relationships
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column "group_id" of relation "searchindex_accesscontrolentry" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 33, in <module>
    sys.exit(load_entry_point('timesketch==20210224', 'console_scripts', 'tsctl')())
  File "/usr/local/lib/python3.6/dist-packages/timesketch/tsctl.py", line 465, in main
    shell_manager.run()
  File "/usr/local/lib/python3.6/dist-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.6/dist-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/dist-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 91, in <module>
    run_migrations_online()
  File "migrations/env.py", line 84, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/tmp/timesketch-20210224/timesketch/migrations/versions/be32626451fb_.py", line 22, in upgrade
    op.add_column('searchindex_accesscontrolentry', sa.Column('group_id', sa.Integer(), nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/local/lib/python3.6/dist-packages/alembic/operations/ops.py", line 1906, in add_column
    return operations.invoke(op)
  File "/usr/local/lib/python3.6/dist-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.6/dist-packages/alembic/operations/toimpl.py", line 131, in add_column
    operations.impl.add_column(table_name, column, schema=schema)
  File "/usr/local/lib/python3.6/dist-packages/alembic/ddl/impl.py", line 231, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.6/dist-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "group_id" of relation "searchindex_accesscontrolentry" already exists

[SQL: ALTER TABLE searchindex_accesscontrolentry ADD COLUMN group_id INTEGER]
```

**Desktop:**
 - OS: Ubuntu 18.04
 - Version: 20210224

**Comment by berggren** [comment]
Hi, thanks for your report.

First: Please backup your database before attempting an upgrade.

Then, try this:
```
1. git clone https://github.com/google/timesketch.git
2. cd timesketch/timesketch
3. tsctl db stamp head
4. tsctl db upgrade
```

Sorry for the lack of documentation here, we are going to update it asap.
We do need to up

**Comment by Kamforka** [comment]
@berggren thank you very much! I'll try it this way then and come back to you with the results!

**Comment by Kamforka** [comment]
@berggren it worked just fine, thank you once more!
By the way, just out of curiosity what does the `tsctl db stamp head` command do?

**Comment by kiddinn** [comment]
what the command does is:

```
This command will add a alembic_version table to your database, and will store the initial migration generated above as the current migration. The head alias always points to the most recent migration, which in our case is the first and only one currently in the repository.
```

you can also google `flask db stamp head` to see more of it, since this is solved, I'll close the issue

**Comment by Kamforka** [comment]
While it was working with my development instance now that I tried to upgrade our production Timesketch I'm getting an error which implies the database upgrade was failing.

I did the following:

```bash
# git clone https://github.com/google/timesketch.git
# cd timesketch/timesketch
tsctl db stamp head
Warning, EMAIL_USER_WHITELIST has been deprecated. Please update timesketch.conf.INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
# tsctl db upgrade
Warning, EMAIL_USER_WHITELIST has been deprecated. Please update timesketch.conf.INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

So no errors during the db upgrade (there is a configuration warning though but that should be okay I think).

Then when I try to startup the server I get the following error traceback:

```python3
[2021-03-15 15:54:00,752] timesketch.app/ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column user.admin does not exist
LINE 1: ...mail AS user_email, "user".active AS user_active, "user".adm...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 259, in decorated_view
    elif not current_user.is_authenticated:
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/usr/local/lib/python3.6/dist-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/usr/local/lib/python3.6/dist-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/usr/local/lib/python3.6/dist-packages/timesketch/app.py", line 153, in load_user
    return User.query.get(user_id)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 982, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 1094, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/loading.py", line 284, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3325, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column user.admin does not exist
LINE 1: ...mail AS user_email, "user".active AS user_active, "user".adm...
                                                             ^

[SQL: SELECT "user".id AS user_id, "user".created_at AS user_created_at, "user".updated_at AS user_updated_at, "user".username AS user_username, "user".password AS user_password, "user".name AS user_name, "user".email AS user_email, "user".active AS user_active, "user".admin AS user_admin 
FROM "user" 
WHERE "user".id = %(param_1)s]
[parameters: {'param_1': '1'}]
```

Then I remembered that I've had this same error shown in my development instance, and there I manually added the `admin` column to the `user` table in postgres. I did the same in prod and now it works there as well:

```
ALTER TABLE "user" ADD COLUMN admin BOOLEAN;
```

So this means that the upgrade path is broken and needs this manual step to be working (hopefully only this step as I haven't conducted an exhaustive check on all the provided functionalities).
