### ISSUE TITLE
Failure when uploading plaso through UI

### ISSUE THREAD

**Issue by herptroll** [google/timesketch#169]
Hi,

I have installed Timesketch and Plaso on an Ubuntu 14.04 machine. When I try to upload a plaso file through the UI I get the following error in celery:

[2016-03-04 15:43:02,600: ERROR/MainProcess] Task timesketch.lib.tasks.run_plaso[241cf68519c4479f8c5740c88ee595e8] raised unexpected: TypeError('ProcessStorage() takes at least 6 arguments (5 given)',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 165, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs) #added self
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 77, in run_plaso
    counter = frontend.ProcessStorage(output_module, storage_file, plugins, queue_producers)
TypeError: ProcessStorage() takes at least 6 arguments (5 given)

This is a standard installation configured out of the box. Seems to be too many or to few arguments?

When i run the following command on the cmd line: psort.py -o timesketch test.plaso
I am able to add a few items to the elasticsearch database, but it fails after a while complaining about:

[INFO] 55000 events added
[INFO] 56000 events added
[INFO] 57000 events added
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 698, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 693, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 642, in ProcessStorage
    self._ProcessStorage()
  File "/usr/bin/psort.py", line 267, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 525, in ProcessStorage
    time_slice=time_slice)
  File "/usr/lib/python2.7/dist-packages/plaso/output/event_buffer.py", line 49, in __exit__
    self.End()
  File "/usr/lib/python2.7/dist-packages/plaso/output/event_buffer.py", line 72, in End
    self.Flush()
  File "/usr/lib/python2.7/dist-packages/plaso/output/event_buffer.py", line 85, in Flush
    self._output_module.WriteEvent(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 86, in WriteEvent
    self.WriteEventBody(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/timesketch_out.py", line 189, in WriteEventBody
    self._events.append(self._GetSanitizedEventValues(event_object))
  File "/usr/lib/python2.7/dist-packages/plaso/output/timesketch_out.py", line 92, in _GetSanitizedEventValues
    message, _ = self._output_mediator.GetFormattedMessages(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/mediator.py", line 120, in GetFormattedMessages
    return event_formatter.GetMessages(self._formatter_mediator, event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/formatters/winjob.py", line 58, in GetMessages
    trigger, u'0x{0:04x}'.format(trigger))
ValueError: Unknown format code 'x' for object of type 'unicode

Anyone had the same problems? Is there a workaround or a fix?

**Comment by berggren** [comment]
Hi Stian,

Sorry for the delay. This is a known issue with Plaso 1.4.0 and Timesketch
2015.12. This is fixed in the repo and will be fixed with the next release.

Can yo try with Plaso 1.3 in the meantime?

**Comment by berggren** [comment]
No response. Closing out. If the problem still exist, please reach out via timesketch-users mailing list:
https://groups.google.com/forum/#!forum/timesketch-users
