### ISSUE TITLE
Auto analyzer execution runs into an error

### ISSUE THREAD

**Issue by blueteam0ps** [google/timesketch#1706]
**Describe the bug**
AUTO_INDEX_ANALYZERS = ['tagger','login'] was set in timesketch.conf

**To Reproduce**
Upload a plaso file after adding the AUTO_INDEX_ANALYZERS into TS config.

Following error is visible in TS logs.

[2021-03-22 12:35:01,230] celery.worker.strategy/INFO Received task: timesketch.lib.tasks.run_index_analyzer[8e7bbf55-35db-4d84-884d-d7e696581c8b]
[2021-03-22 12:35:01,298] celery.app.trace/ERROR Task timesketch.lib.tasks.run_index_analyzer[8e7bbf55-35db-4d84-884d-d7e696581c8b] raised unexpected: TypeError("__init__() missing 1 required positional argument: 'sketch_id'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/app.py", line 198, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/tasks.py", line 481, in run_index_analyzer
    analyzer = analyzer_class(index_name=index_name, **kwargs)

**Comment by kiddinn** [comment]
ok, so I will need to remove the `AUTO_INDEX_ANALYZERS` out of the config file.

But `tagger` and `login` are not index analyzers, but sketch analyzers... so you'll need to modify this to be:

```
AUTO_SKETCH_ANALYZERS = ['tagger', 'login']
```

**Comment by blueteam0ps** [comment]
Thanks Kiddi! I just modified as you suggested and it works.

**Comment by kiddinn** [comment]
great, I also added #1710 to make sure that this doesn't cause an exception to be raised, in case others accidentally use the index analyzers as an opposed to the sketch ones.
