### ISSUE TITLE
Error exporting ver large sketch

### ISSUE THREAD

**Issue by alexgoedeke** [google/timesketch#1749]
**Describe the bug**
When trying to run the export function from the web UI, the command fails with 'Failed response: [500] Internal Server Error'. The same happens with the API from a notebook.

**To Reproduce**
1. archive the sketch
2. click on export

**Expected behavior**
The export function should export the sketch and download it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 78.10.0esr

**Additional context**

TImesketch version: 20210224

Error from timesketch logfile:
```
[2021-04-29 13:58:18,915] timesketch.app/ERROR Exception on /api/v1/sketches/1/archive/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 158, in post
    return self._export_sketch(sketch)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 324, in _export_sketch
    self._export_view(view, sketch, zip_file)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 373, in _export_view
    result = self.datastore.search(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/datastores/elastic.py", line 504, in search
    return self.client.search(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 1548, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 50, in _make_path
    return "/" + "/".join(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 52, in <genexpr>
    quote(_escape(p), b",*")
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 20, in _escape
    value = ",".join(value)
TypeError: sequence item 0: expected str instance, int found
```

**Comment by GenericUser450** [comment]
I'm experiencing this as well, but without archiving it. The web UI flashes and nothing happens. When I check the error log I'm seeing the following:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 158, in post
    return self._export_sketch(sketch)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 331, in _export_sketch
    self._export_tagged_events(sketch, zip_file)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 273, in _export_tagged_events
    result_obj, meta = utils.run_aggregator(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/utils.py", line 123, in run_aggregator
    aggregator = agg_class(sketch_id=sketch_id, index=index)
TypeError: __init__() got an unexpected keyword argument 'index'
`

I've tried it on a Sketch with data populated as well as on a fresh install via Docker on a brand new sketch with nothing in it. Same happens both times

**Comment by jaegeral** [comment]
How large is your sketch? Is there any hepful output before or after this stack?

**Comment by alexgoedeke** [comment]
@jaegeral about 5 million events

**Comment by tconqueror** [comment]
I had the same problem, hope it works again soon because old sketches use a lot of storage

**Comment by jaegeral** [comment]
Ok so it seems this is because of memory allocation, I am not sure when and how we can tackle this as the export feature of a whole sketch is not a common feature that is being used.

As an interim solution I suggest to export data in chunks via the API. I know this is not ideal.
