### ISSUE TITLE
Jsonl content too long

### ISSUE THREAD

**Issue by lprat** [google/timesketch#1754]
**Is your feature request related to a problem? Please describe.**
When I upload jsonl, in some case, the length of line is very too long. When API upload flush events to elastic then it get 'error 413' (line too long) and this error break timeline.
```
[2021-04-29 19:19:14,491] timesketch.tasks/ERROR Error: TransportError(413, '')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/tasks.py", line 681, in run_csv_jsonl
    es.import_event(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/datastores/elastic.py", line 983, in import_event
    _ = self.flush_queued_events()
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/datastores/elastic.py", line 1012, in flush_queued_events
    results = self.client.bulk(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 448, in bulk
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.TransportError: TransportError(413, '')
[2021-04-29 19:19:14,719] celery.app.trace/INFO Task timesketch.lib.tasks.run_csv_jsonl[ed224b9758ec43c18862f28350eafbff] succeeded in 51.03816904872656s: None
[2021-04-29 19:19:37,105] timesketch.tasks/INFO Index timeline [spyre_pole3] to index [1619722543.3322954spyre_pole3] (source: jsonl)
[2021-04-29 19:19:38,409] timesketch.elasticsearch/ERROR Errors while attempting to upload events.
[2021-04-29 19:19:38,410] timesketch.elasticsearch/ERROR Unable to upload document, and unable to log the error itself.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/datastores/elastic.py", line 1074, in flush_queued_events
    'Unable to upload document: {0:s} to index {1:s} - '
TypeError: unsupported format string passed to NoneType.__format__
```

**Describe the solution you'd like**
It's possible to add validate test to verify length of event (https://github.com/google/timesketch/blob/master/timesketch/lib/tasks.py#L666).
In timesketch.conf, you can add option "MAX_LENGTH_JSONL_EVENT" because it's possible to configure elastic to have no standard LENGHT (elasticsearch.yml => http.max_content_length & http.max_initial_line_length).

Thanks
Lionel

**Comment by jaegeral** [comment]
Similar to the PR, 
Looks like we have not merged that in over a year and as far as I can tell, we have not seen any issues from other people, so I am going to close this out, thx @lprat still for the contribution, if one would run in the issue again we can re-visit the PR.
