### ISSUE TITLE
Remove sleep() usage in Sigma Tagger

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#1782]
This sleep timer should be removed and replaced with something more robust, e.g. waiting for the last query to finish etc.

https://github.com/google/timesketch/blob/a5f086094409446ae408d71f89a3df4c1ba085c5/timesketch/lib/analyzers/sigma_tagger.py#L79

**Comment by jaegeral** [comment]
This is the exact error issue:
```
elasticsearch.exceptions.TransportError: TransportError(500, 'search_phase_execution_exception', 'Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting.')
[2021-05-21 07:07:43,789] timesketch.analyzers.sigma_tagger/ERROR Timeout executing search for win_susp_ldap_dataexchange.yml: TransportError(500, 'search_phase_execution_exception', 'Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting.') waiting for 10 seconds
Traceback (most recent call last):
  File "/usr/local/src/timesketch/timesketch/lib/analyzers/sigma_tagger.py", line 68, in run
    tagged_events_counter = self.run_sigma_rule(
  File "/usr/local/src/timesketch/timesketch/lib/analyzers/sigma_tagger.py", line 40, in run_sigma_rule
    for event in events:
  File "/usr/local/src/timesketch/timesketch/lib/analyzers/interface.py", line 948, in event_stream
    for event in event_generator:
  File "/usr/local/src/timesketch/timesketch/lib/datastores/elastic.py", line 625, in search_stream
    result = self.search(
  File "/usr/local/src/timesketch/timesketch/lib/datastores/elastic.py", line 565, in search
    _search_result = self.client.search(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 1547, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.TransportError: TransportError(500, 'search_phase_execution_exception', 'Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting.')
```

**Comment by jaegeral** [comment]
And it seems only to happen if to many celery workers are running as the analyzer was started on many timelines in paralell.

**Comment by jaegeral** [comment]
Was fixed with: https://github.com/google/timesketch/pull/1960
