### ISSUE TITLE
Wrong initial parameters get cached for forever

### ISSUE THREAD

**Issue by kriss332** [google/timesketch#1800]
**Describe the bug**
While doing first login through timesketch-importer cli tool, if the parameter related to authentication type is spelled wrongly, there seems to be no way to reset it back. TImesketch container saves whatever is passed to it.

**To Reproduce**
1. Run timesketch_importer on a freshly deployed docker instance to upload a CSV file as follows- timesketch_importer somefile.csv
2. You will be asked URL, feed it. You will be asked for auth type (userpass or OAUTH), I entered a typo/wrong-value in this step.
3.  The authentication fails. 
4. Every following attempt with all possible parameters doesn't change the exception message. Hosenstly I am new to timesketch and don't know if there exists a method to solve this.

**Expected behavior**
I needed an option to purge the settings that got saved in timesketch container while using timesketch_importer tool.

**Screenshots**
---

**Desktop (please complete the following information):**
 - Ubuntu 20
 - Tool - timesketch_importer CLI tool
 - timesketch_importer --version
    API Client Version: 20210416
    Importer Client Version: 20210402

**Additional context**
The exception message-

[2021-06-01 16:24:45,899] timesketch_importer.importer_frontend/INFO Creating a client.
[2021-06-01 16:24:46,283] timesketch_importer.importer_frontend/INFO Client created.
[2021-06-01 16:24:46,283] timesketch_importer.importer_frontend/INFO Saving TS config.
Traceback (most recent call last):
  File "/home/kriss/.local/bin/timesketch_importer", line 8, in <module>
    sys.exit(main())
  File "/home/kriss/.local/lib/python3.8/site-packages/tools/timesketch_importer.py", line 419, in main
    my_sketch = ts_client.create_sketch(sketch_name)
  File "/usr/local/lib/python3.8/dist-packages/timesketch_api_client/client.py", line 353, in create_sketch
    response_dict = error.get_response_json(response, logger)
  File "/usr/local/lib/python3.8/dist-packages/timesketch_api_client/error.py", line 93, in get_response_json
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kiddinn** [comment]
the API client does have a way to fix this... however the timesketch importer is missing a flag to overwrite the settings.

For now there are two ways:

1. Delete the ~/.timesketchrc file
2. Open up an ipython shell and type

```python
from timesketch_api_client import config
c = config.get_client(confirm_choices=True)
```

And answer the questions there, adn then the import client will start working again.

However, I can also just add this flag to the importer client to make it accessible from there.

**Comment by kriss332** [comment]
@kiddinn thanks alot for the support. Kudos to you folks.
Moreover I had to remove ~/.timesketch.token file as well. I would request you to add this to the official documentation as well.
BTW what did you mean by your last line? *However, I can also just add this flag to the importer client to make it accessible from there.*

**Comment by kiddinn** [comment]
I added a new parameter to the timesketch importer, in #1791, that will add a `--re-prompt` parameter to the importer CLI, that will trigger re-asking all the parameters, in case you made a mistake
