### ISSUE TITLE
Error Exception on /api/v1/upload/ [POST]

### ISSUE THREAD

**Issue by SkyBlue-B** [google/timesketch#1811]
Hi, 

I am facing an issue with upload via Web UI. 
The uploaded data is stuck on "indexing in progress..."

Error logs
timesketch.app/ERROR Exception on /api/v1/upload/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/upload.py", line 442, in post
    return self._upload_file(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/upload.py", line 326, in _upload_file
    return self._upload_and_index(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/upload.py", line 235, in _upload_and_index
    pipeline = tasks.build_index_pipeline(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/tasks.py", line 252, in build_index_pipeline
    index_task_class = _get_index_task_class(file_extension)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/tasks.py", line 221, in _get_index_task_class
    raise KeyError('No task that supports {0:s}'.format(file_extension))
KeyError: 'No task that supports json'

**Comment by SkyBlue-B** [comment]
Instead of json, used plaso and worked. 

Can you help what this means? 
/usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used return io.open(fd, *args, **kwargs)

**Comment by jaegeral** [comment]
Hm can you maybe post the first few lines of your json file (or the complete file if possible)? And what was the file extension of the file? 

But I assume the issue is that your file was a json file, while the upload only accepts jsonl:
https://github.com/google/timesketch/blob/master/timesketch/lib/tasks.py#L218

**Comment by jaegeral** [comment]
@SkyBlue-B any update?

**Comment by SkyBlue-B** [comment]
@jaegeral the issue is fixed, thanks, was able to upload plaso file
