### ISSUE TITLE
elasticsearch timesketch_label nested path exception 

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1833]
**Describe the bug**
When accessing a sketch an internal server error is thrown with the following exception:
```
[2021-06-17 08:24:08,844] timesketch.app/ERROR Exception on /api/v1/sketches/2/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/sketch.py", line 459, in get
    filter_labels=self.datastore.get_filter_labels(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/datastores/elastic.py", line 713, in get_filter_labels
    result = self.client.search(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 1547, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.TransportError: TransportError(500, 'search_phase_execution_exception', '[nested] nested path [timesketch_label] is not nested')

```
The exact reson for this exception is unknown it was working then sudenly it isn't anymore with no addtional data ingestion. 
**To Reproduce**

1. Import jsonl data ```streamer.set_data_label("jsonl")``` into timesketch (plaso,dictionary data).
2. run tagger analyzer that tags varying types of events.

theses were the activities done on the sketch and it was working correctly until it wasn't

**Expected behavior**
No exception is thrown and the data still accesible.

**Desktop (please complete the following information):**
-OS:Ubuntu 20.04.2 LTS
-Browser : Firefox
-Version: 86.0

**Additional context**
TimeSketch Version: 20210602
API Client Version: 20210319
Importer Client Version: 20210305

**Comment by berggren** [comment]
Good catch! This has been fixed, but for already deployed servers you need to update the file /etc/timesketch/generic.mappings

With the updated content here: https://github.com/google/timesketch/blob/master/data/generic.mappings
