### ISSUE TITLE
Connection Refused Error when Psorting

### ISSUE THREAD

**Issue by BannersSecret** [google/timesketch#184]
Hi,

I have a VM running Timesketch setup in my lab, and another VM on my local laptop also with Timesketch. 

I'm trying to send data to the Timesketch server, however get an error saying connection is refused:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 698, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 693, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 642, in ProcessStorage
    self._ProcessStorage()
  File "/usr/bin/psort.py", line 267, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 520, in ProcessStorage
    output_module, deduplicate_events)
  File "/usr/lib/python2.7/dist-packages/plaso/output/event_buffer.py", line 38, in __init__
    self._output_module.WriteHeader()
  File "/usr/lib/python2.7/dist-packages/plaso/output/timesketch_out.py", line 216, in WriteHeader
    if not self._elastic_db.client.indices.exists(self._index_name):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 226, in exists
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 105, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f0eca864e10>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f0eca864e10>: Failed to establish a new connection: [Errno 111] Connection refused)

Google suggests installing an older version of Elasticsearch, but that doesn't cure it.

Anyone experienced this?

Cheers,

A

**Comment by BannersSecret** [comment]
Sorry, my bad. ElasticSearch wasn't running.

Solution, in case someone else hits on it:

sudo /etc/init.d/elasticsearch start
