### ISSUE TITLE
Adding labels breaks TS

### ISSUE THREAD

**Issue by rushattac** [google/timesketch#1859]
**Describe the bug**
By adding a label to a timeline in a sketch that sketch is no loanger accessable.
Also this might be unrelated but when adding a star to an event then trying to filter by all stared event the search doesn't work.

**To Reproduce**
1. create a sketch.
2. create a timeline
3. add label.
4. refresh page

**Expected behavior**
to be able to still use timesketch when adding a labels

**Desktop (please complete the following information):**
-OS:Ubuntu 20.04.2 LTS
-Browser : Firefox
-Version: 86.0

**Additional context**
wsgi_error logs related to the issue
```
[2021-06-29 12:09:49,440] timesketch.app/ERROR Exception on /api/v1/sketches/3/explore/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/explore.py", line 224, in post
    result = self.datastore.search(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/datastores/elastic.py", line 521, in search
    query_dsl = self.build_query(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/datastores/elastic.py", line 367, in build_query
    labels.append(chip['value'])
KeyError: 'value'
```

**Comment by rushattac** [comment]
recreating the docker image fixed the issue
