### ISSUE TITLE
Error when processing Plaso file

### ISSUE THREAD

**Issue by BannersSecret** [google/timesketch#188]
Hi,

I have been successfully processing Plaso files for the last few days, but have hit upon one particular file which crashes out the processing around the 300k events mark, with the following error:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 698, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 693, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 642, in ProcessStorage
    self._ProcessStorage()
  File "/usr/bin/psort.py", line 267, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 525, in ProcessStorage
    time_slice=time_slice)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 389, in ProcessEventsFromStorage
    for event_object in storage_file.GetSortedEntries(time_range=time_slice):
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 1664, in GetSortedEntries
    event_object = self.GetSortedEntry(time_range=time_range)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 1641, in GetSortedEntry
    next_event_object = self._GetEventObject(stream_number)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 1054, in _GetEventObject
    event_object_data)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 799, in ReadSerialized
    return json_decoder.decode(json_string)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 456 (char 455)

Is this to do with the contents of the Plaso file, or the decoder.py file?

Thanks,

A

**Comment by berggren** [comment]
Hi! This looks like it a Plaso issue. Could you open a new issue over at https://github.com/log2timeline/plaso/issues/new

Thanks!
