### ISSUE TITLE
Import fails when specifying an uppercase index name

### ISSUE THREAD

**Issue by mpilking** [google/timesketch#1890]
**Describe the bug**
The following error occurs when using uppercase characters in an index name. The warning message says "Attempting to create an index that already exists", which is not correct. There was no index by the name of "SANS-SIFT3-triage". Instead, it turns out the issue is that uppercase index names are not supported by Elasticsearch: https://github.com/elastic/elasticsearch/issues/31262

```
[2021-08-05 22:17:34,593] celery.worker.consumer.connection/INFO Connected to redis://redis:6379//
[2021-08-05 22:17:34,639] celery.worker.consumer.mingle/INFO mingle: searching for neighbors
[2021-08-05 22:17:35,679] celery.worker.consumer.mingle/INFO mingle: all alone
[2021-08-05 22:17:35,710] celery.apps.worker/INFO celery@b4f7a93d10b3 ready.
[2021-08-05 22:30:15,446] celery.worker.strategy/INFO Received task: timesketch.lib.tasks.run_plaso[5088387abc9c4d339b90d7c06d983207]  
[2021-08-05 22:30:15,470] timesketch.elasticsearch/WARNING Attempting to create an index that already exists (plaso-SANS-SIFT3 - False)
[2021-08-05 22:30:15,471] timesketch.tasks/INFO Index timeline [SANS-SIFT3-triage] to index [plaso-SANS-SIFT3] (source: plaso)
[2021-08-05 22:30:17,502] timesketch.tasks/ERROR Unable to close index: plaso-SANS-SIFT3 - index not found
[2021-08-05 22:30:17,503] celery.app.trace/INFO Task timesketch.lib.tasks.run_plaso[5088387abc9c4d339b90d7c06d983207] succeeded in 2.052665342999944s: '2021-08-05 22:30:16,831 [INFO] (MainProcess) PID:16 <data_location> Determined data location: /usr/share/plaso
2021-08-05 22:30:17,114 [INFO] (MainProcess) PID:16 <elastic_ts> Timeline identifier: 5
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 598, in ProcessStorage
    analysis_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 1049, in ExportEvents
    output_module.WriteHeader()
  File "/usr/lib/python3/dist-packages/plaso/output/elastic_ts.py", line 86, in WriteHeader
    self._CreateIndexIfNotExists(self._index_name, self._mappings)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 223, in _CreateIndexIfNotExists
    self._client.indices.create(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 84,...'
(END)
```

**To Reproduce**
Use a timesketch_importer command such as the following, specifically using UPPERCASE letters in the index name:

`timesketch_importer --host http://127.0.0.1 --index_name plaso-SANS-SIFT3 --timeline_name SANS-SIFT3-triage /cases/processor/SANS-SIFT3.plaso`

**Expected behavior**
Ideally timesketch_importer would warn not to include uppercase letters in the index name. Or lower the case for the user.

**Screenshots**
Here's a look at the celery logs from worker.log:

![image](https://user-images.githubusercontent.com/5453480/128588679-355b1c5e-6a79-4ab7-a092-c61071a710ff.png)

**Desktop (please complete the following information):**
Ubuntu 20.04 with timesketch docker install. Here is the version of timesketch_importer installed:

```
$ timesketch_importer --version
API Client Version: 20210416
Importer Client Version: 20210402
```

**Comment by shreyassai123** [comment]
Hello, I'm interested in working on this issue and contribute to the project, let me know if I can help. Thanks!

**Comment by berggren** [comment]
Interesting, I didn't know ES didn't like uppercase in index name. Quick question @mpilking why do you need to specify the index name here? If you leave it out we will generate one for you. You should only have to set the timeline name. I'm curious of the use-case here :)

Also, this doesn't mean we shouldn't fix the exception case. We should probably just lower case the name.

@shreyassai123 if you are interested in fixing this, let me know. To get you started, here is a good start: https://github.com/google/timesketch/blob/master/importer_client/python/timesketch_import_client/importer.py

**Comment by mpilking** [comment]
> Interesting, I didn't know ES didn't like uppercase in index name. Quick question @mpilking why do you need to specify the index name here? If you leave it out we will generate one for you. You should only have to set the timeline name. I'm curious of the use-case here :)

Sorry for the late reply @berggren. I missed the notification and just happened to check on this today.

The main reason I wanted to specify the index name was to force it through an ES ingest pipeline to do additional parsing. I was using this process: https://github.com/InsaneTechnologies/elasticsearch-plaso-pipelines. However, we later determined it was causing some dropped events, so I'm no longer doing this. Still, it's nice to be able to provide a deterministic index name so it's clear what is in it.

**Comment by berggren** [comment]
Cleaning up bug queue - Closing this out
