### ISSUE TITLE
Recursion Error in GeoIP analyzer when configuration values not set

### ISSUE THREAD

**Issue by sydp** [google/timesketch#1898]
A RecursionError occurs in the Client Adapter when configuration values are not set.

**To Reproduce**
1. Run the GeoIP analyzer

```
timesketch.tasks/INFO [geo_ip_maxmind_db] result: Traceback (most recent call last):
  File "/usr/local/src/timesketch/timesketch/lib/analyzers/interface.py", line 995, in run_wrapper
    result = self.run()
  File "/usr/local/src/timesketch/timesketch/lib/analyzers/geoip.py", line 282, in run
    response = client.ip2geo(ip_address)
  File "/usr/local/src/timesketch/timesketch/lib/analyzers/geoip.py", line 95, in __exit__
    return self.__exit__(exc_type, exc_value, traceback)
  File "/usr/local/src/timesketch/timesketch/lib/analyzers/geoip.py", line 95, in __exit__
    return self.__exit__(exc_type, exc_value, traceback)
  File "/usr/local/src/timesketch/timesketch/lib/analyzers/geoip.py", line 95, in __exit__
    return self.__exit__(exc_type, exc_value, traceback)
  [Previous line repeated 957 more times]
RecursionError: maximum recursion depth exceeded 
```

**Expected behavior**
Should report "MaxMind Database configuration not set."

**Comment by jaegeral** [comment]
According to the PR, this issue is fixed so I am closing this issue
