### ISSUE TITLE
No indexed data available after ingesting 3.3GB plaso file

### ISSUE THREAD

**Issue by mister-turtle** [google/timesketch#1934]
**Describe the bug**
Importing a 3.3GB plaso file through the web interface has resulted in just showing "Indexing in progress" under the investigation screen for over an hour. The Elasticsearch instance was taking a fair bit of CPU for a while, and document count was increasing, however now it is stopped and the data is still unavailable.
  
No data has shown up under the `/sketch/1/explore` interface. Monitoring the ES index I can see nothing else is being added.

```shell
Every 5.0s: curl http://127.0.0.1:9200/_cat/indices?v=true&s=index                                                                                                                                                        12536c45c0d4: Fri Sep  3 11:17:06 2021

health status index                            uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   09881955a21b480d8a56a7c7e53c0774 eMnvRAfBSn6719c67NeP2g   1   1    5844839            0      1.6gb          1.6gb
```
**To Reproduce**
1. Installed via the latest `deploy_timesketch.sh` script
2. `cd /opt/`
3. `~/timesketch_deploy.sh`
4. Created user
5. Created a plaso file with latest log2timeline/plaso docker image of a mounted volume
6. Uploaded to timesketch web interface

**Expected behavior**
Plaso file is parsed and data available.
If an upload, indexing, or other part of the process fails I would expect errors to bubble up to the client

**Additional context**
I've checked the `docker logs` of the containers and not spotted anything, but I'm unsure where to look.

**Comment by mister-turtle** [comment]
I've found some logs around the time of the ingestion from `timesketch_timesketch-worker_1`
```
[2021-09-03 09:44:40,992] timesketch.tasks/INFO Index timeline [REDACTED] to index [09881955a21b480d8a56a7c7e53c0774] (source: plaso)
[2021-09-03 10:20:56,458] celery.worker.consumer.consumer/WARNING consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/usr/local/lib/python3.8/dist-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.8/dist-packages/kombu/transport/redis.py", line 1083, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.8/dist-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.8/dist-packages/kombu/transport/redis.py", line 688, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.8/dist-packages/kombu/transport/redis.py", line 698, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 3185, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.8/dist-packages/redis/client.py", line 3159, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 700, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 310, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 242, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 187, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2021-09-03 10:21:13,295] celery.worker.consumer.connection/INFO Connected to redis://redis:6379//
[2021-09-03 10:21:13,301] celery.worker.consumer.mingle/INFO mingle: searching for neighbors
[2021-09-03 10:21:14,320] celery.worker.consumer.mingle/INFO mingle: all alone
[2021-09-03 10:21:14,336] celery.apps.worker/INFO celery@5b8584f40d69 ready.
```

**Comment by mister-turtle** [comment]
Re-uploading this file seems to have worked, however the previous file still says "indexing".

**Comment by jaegeral** [comment]
yes that previous thing will stay there forever, you can just delete it.

**Comment by jaegeral** [comment]
yes that previous thing will stay there forever, you can just delete it.

**Comment by mister-turtle** [comment]
Will there be any attempt to fix UX issues around failed uploads not being reported? I had to monitor ES from within the docker environment to ascertain nothing else was happening, and closing the issue without addressing that seems like the pipeline failure will just be glossed over.
