### ISSUE TITLE
graph display error

### ISSUE THREAD

**Issue by SydoQQ** [google/timesketch#1957]
![image](https://user-images.githubusercontent.com/25013728/135112527-a7953d20-1f3a-44b4-b1c5-c3b92b840f45.png)
![image](https://user-images.githubusercontent.com/25013728/135112597-89ba3501-7d24-4426-90a3-7e3cc4060155.png)

**Stack call**

b50d/t.exports
chunk-vendors.a6947d36.js:138496:12
b50d/t.exports
chunk-vendors.a6947d36.js:138332:9
5270/t.exports
chunk-vendors.a6947d36.js:98047:9
(Async: promise callback) 0a06/l.prototype.request
chunk-vendors.a6947d36.js:967:22
0a06/</l.prototype[t]
chunk-vendors.a6947d36.js:993:16
1d2b/t.exports/<
chunk-vendors.a6947d36.js:7076:14
generateGraphFromPlugin
RestApiClient.js:294:25
buildGraph
Graph.vue:411
click
Graph.vue:1:4926
ne
chunk-vendors.a6947d36.js:26344:25
n
chunk-vendors.a6947d36.js:26567:13
Jr/a._wrapper
chunk-vendors.a6947d36.js:30988:24
(Async: EventListener.handleEvent) Jr
chunk-vendors.a6947d36.js:30992:11
xe
chunk-vendors.a6947d36.js:26596:6
ta
chunk-vendors.a6947d36.js:31022:2
w
chunk-vendors.a6947d36.js:30169:22
d
chunk-vendors.a6947d36.js:30060:10
b
chunk-vendors.a6947d36.js:30153:18
d
chunk-vendors.a6947d36.js:30058:8
b
chunk-vendors.a6947d36.js:30153:18
d
chunk-vendors.a6947d36.js:30058:8
b
chunk-vendors.a6947d36.js:30153:18
d
chunk-vendors.a6947d36.js:30058:8
b
chunk-vendors.a6947d36.js:30153:18
d
chunk-vendors.a6947d36.js:30058:8
b
chunk-vendors.a6947d36.js:30153:18
d
chunk-vendors.a6947d36.js:30058:8
b
chunk-vendors.a6947d36.js:30153:18
d
chunk-vendors.a6947d36.js:30058:8
Fr/<
chunk-vendors.a6947d36.js:30556:6
Pn/t.prototype._update
chunk-vendors.a6947d36.js:28231:18
i
chunk-vendors.a6947d36.js:28319:9
2b0e/</ni.prototype.get
chunk-vendors.a6947d36.js:28705:24
ni
chunk-vendors.a6947d36.js:28694:11
jn
chunk-vendors.a6947d36.js:28326:2
2b0e/</ki.prototype.$mount
chunk-vendors.a6947d36.js:32462:9
init
chunk-vendors.a6947d36.js:27458:12
p
chunk-vendors.a6947d36.js:30080:8
d
chunk-vendors.a6947d36.js:30041:8
b
chunk-vendors.a6947d36.js:30153:18
d
chunk-vendors.a6947d36.js:30058:8
Fr/<
chunk-vendors.a6947d36.js:30556:6

**wsgi_error.log**

timesketch.app/ERROR **Exception on /api/v1/sketches/1/graph/ [POST]**
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/graph.py", line 348, in post
    cytoscape_json = graph.generate().to_cytoscape()
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/graphs/win_logins.py", line 46, in generate
    user = self.graph.add_node(username, {'type': 'user'})
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/graphs/interface.py", line 64, in add_node
    node = Node(label, attributes)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/graphs/interface.py", line 137, in __init__
    self.id = self._generate_id()
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/graphs/interface.py", line 146, in _generate_id
    return hashlib.md5(id_string.encode('utf-8')).hexdigest()
**AttributeError: 'NoneType' object has no attribute 'encode'**

**Comment by jaegeral** [comment]
@berggren  as the expert for the graph views.

**Comment by jaegeral** [comment]
Graphs have been ported over, closing in fav of the new feature.
