### ISSUE TITLE
Is run_tests.py still supported or should it be removed?

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#1985]
```
./run_tests.py 
Traceback (most recent call last):
  File "./run_tests.py", line 64, in <module>
    main()
  File "./run_tests.py", line 61, in main
    run_python(args)
  File "./run_tests.py", line 29, in run_python
    run_python_tests(coverage=args.coverage)
  File "./run_tests.py", line 20, in run_python_tests
    subprocess.check_call(
  File "/usr/lib64/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nosetests'
```

**Comment by joachimmetz** [comment]
Never mind see the issue that nosetests binary cannot be found on the test machine
