### ISSUE TITLE
version of elasticsearch-py in requirements.txt causing Import error

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#1986]
Tested with the following tox configuration on HEAD

```
[tox]
envlist = py3{6,7,8,9,10},pylint

[testenv]
pip_pre = True
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -rrequirements.txt
    -rtest_requirements.txt
commands =
    py3{6,7,8,9,10}: ./run_tests.py

[testenv:pylint]
skipsdist = True
pip_pre = True
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -rrequirements.txt
    -rtest_requirements.txt
    pylint >= 2.9.0, < 2.10.0
commands =
    pylint --version
    pylint --rcfile=.pylintrc api_client cli_client importer_client timesketch tests test_tools
```

Ran: `tox -epy39`

```
Traceback (most recent call last):
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.9/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.9/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/timesketch/timesketch/api/v1/resources/__init__.py", line 28, in <module>
    from timesketch.lib.datastores.elastic import ElasticsearchDataStore
  File "/timesketch/timesketch/lib/datastores/elastic.py", line 27, in <module>
    from elasticsearch import Elasticsearch
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/elasticsearch/__init__.py", line 24, in <module>
    from .client import Elasticsearch
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 5, in <module>
    from ..transport import Transport
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/elasticsearch/transport.py", line 5, in <module>
    from .connection import Urllib3HttpConnection
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/elasticsearch/connection/__init__.py", line 2, in <module>
    from .http_requests import RequestsHttpConnection
  File "/timesketch/.tox/py39/lib/python3.9/site-packages/elasticsearch/connection/http_requests.py", line 3, in <module>
    from base64 import decodestring
ImportError: cannot import name 'decodestring' from 'base64' (/usr/lib64/python3.9/base64.py)
```

Updating the version of elasticsearch-py in requirements.txt to `elasticsearch<=8` makes the issue go away

**Comment by jaegeral** [comment]
As we migrated away from ES to OpenSearch that should be fixed a while ago.
