### ISSUE TITLE
CI tests failing with: ImportError cannot import name 'json_available' from 'flask'

### ISSUE THREAD

**Issue by joachimmetz** [google/timesketch#1988]
https://github.com/google/timesketch/runs/3914737857?check_suite_focus=true#step:5:7

Unclear why the CI tests are failing

```
======================================================================
ERROR: Failure: ImportError (cannot import name 'json_available' from 'flask' (/usr/local/lib/python3.8/dist-packages/flask/__init__.py))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/timesketch/timesketch/timesketch/api/v1/resources_test.py", line 24, in <module>
    from timesketch.lib.testlib import BaseTest
  File "/home/runner/work/timesketch/timesketch/timesketch/lib/testlib.py", line 22, in <module>
    from flask_testing import TestCase
  File "/usr/lib/python3/dist-packages/flask_testing/__init__.py", line 13, in <module>
    from .utils import TestCase, LiveServerTestCase
  File "/usr/lib/python3/dist-packages/flask_testing/utils.py", line 38, in <module>
    from flask import json_available, templating, template_rendered
ImportError: cannot import name 'json_available' from 'flask' (/usr/local/lib/python3.8/dist-packages/flask/__init__.py)
-------------------- >> begin captured logging << --------------------
```

**Comment by jaegeral** [comment]
AFAIK the tests are working in the meantime, so closing this one, lmk if that is a wrong assumption
