### ISSUE TITLE
UI aggregate - altair limit to 5000 return events

### ISSUE THREAD

**Issue by lprat** [google/timesketch#2053]
When you use aggregate UI, you can choose the "Number of results to return", if you choose number > 5000 then make error:

```
[2021-11-29 08:09:21,888] timesketch.app/ERROR Exception on /api/v1/sketches/2/aggregation/explore/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/aggregation.py", line 532, in post
    meta['vega_spec'] = result_obj.to_chart(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/aggregators/interface.py", line 131, in to_chart
    return chart.to_dict()
  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/v4/api.py", line 363, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/v4/api.py", line 84, in _prepare_data
    data = _pipe(data, data_transformers.get())
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/data.py", line 19, in default_data_transformer
    return curried.pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/altair/utils/data.py", line 80, in limit_rows
    raise MaxRowsError(
altair.utils.data.MaxRowsError: The number of rows in your dataset is greater than the maximum allowed (5000). For information on how to plot larger datasets in Altair, see the documentation
```
You can disable this error by disable: "alt.data_transformers.disable_max_rows()"
Ref: https://altair-viz.github.io/user_guide/faq.html#disabling-maxrowserror

Can you tell me if max value is a desire of your team ? If yes, can you add option in config to disable this error ?

Thank.
Lionel

**Comment by jaegeral** [comment]
`Hi @lprat sorry for the (very) long delay on this PR. The old UI that this PR is on is deprecated in favour of a new, refreshed UI using material design. We will not be merging any new features to the old UI.`

Applies here as well, so I am closing this issue in favour of the material design
