### ISSUE TITLE
Sigma '\foo.exe' in a rule is causing yaml parsing to fail

### ISSUE THREAD

**Issue by jaegeral** [google/timesketch#2122]
A rule like: 
```
MOCK_SIGMA_ENDSWITH = """
title: endswith example
id: 99fbfdbf-23bf-436f-9c4a-72e49ab10b90
description: Similar to win_susp_net_execution.yml
author: Alexander Jaeger
detection:
    selection:
        Image|endswith:
            - '\foo.exe'
            - '\bar.exe'
    condition: selection
"""
```

Will cause: 
```
ERROR: Test getting sigma rule by text.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/timesketch/timesketch/lib/sigma_util_test.py", line 237, in test_get_rule_by_text
    rule = sigma_util.get_sigma_rule_by_text(MOCK_SIGMA_ENDSWITH)
  File "/usr/local/src/timesketch/timesketch/lib/sigma_util.py", line 464, in get_sigma_rule_by_text
    for doc in rule_yaml_data:
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 127, in load_all
    loader = Loader(stream)
  File "/usr/local/lib/python3.8/dist-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.8/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/lib/python3.8/dist-packages/yaml/reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x000c: special characters are not allowed
  in "<unicode string>", position 207
-------------------- >> begin captured logging << --------------------
timesketch.lib.sigma: ERROR: Sigma parsing error rule No detection definitions found
timesketch.lib.sigma: ERROR: Error generating rule Aggregations not implemented for this backend
--------------------- >> end captured logging << ---------------------
```

**Comment by jaegeral** [comment]
Closing it out, Sigma in Timesketch is likely to be deprecated or not maintained for a bit.
