### ISSUE TITLE
Timesketch stories don't work, nothing appears.

### ISSUE THREAD

**Issue by S-Nicholas** [google/timesketch#2146]
Timesketch stories don't work, nothing appears, request Ok but Js errors.
![image](https://user-images.githubusercontent.com/75032634/154103678-7d2949fa-a7d9-4e56-81ec-c49fb27b475b.png)
![image](https://user-images.githubusercontent.com/75032634/154103440-c342913b-25d5-47c7-8d46-fb382b58a5bc.png)

**Comment by jaegeral** [comment]
Yep can confirm that

**Comment by jaegeral** [comment]
```
vue.runtime.esm.js:1897 TypeError: nr(...) is not a function
    at o.toHtml (StoryContent.vue:240:14)
    at StoryContent.vue?8401:1:1755
    at o.Re [as _l] (vue.runtime.esm.js:2646:16)
    at o.sr (StoryContent.vue?8401:1:703)
    at o.t._render (vue.runtime.esm.js:3569:22)
    at o.i (vue.runtime.esm.js:4081:21)
    at ii.get (vue.runtime.esm.js:4495:25)
    at ii.run (vue.runtime.esm.js:4570:22)
    at Kn (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
ae @ vue.runtime.esm.js:1897
re @ vue.runtime.esm.js:1888
ne @ vue.runtime.esm.js:1848
t._render @ vue.runtime.esm.js:3571
i @ vue.runtime.esm.js:4081
ii.get @ vue.runtime.esm.js:4495
ii.run @ vue.runtime.esm.js:4570
Kn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
ce @ vue.runtime.esm.js:1915
Promise.then (async)
oe @ vue.runtime.esm.js:1942
ge @ vue.runtime.esm.js:1999
ei @ vue.runtime.esm.js:4418
ii.update @ vue.runtime.esm.js:4560
gt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ StoryContent.vue:184
g @ lodash.js:10401
x @ lodash.js:10450
b @ lodash.js:10438
setTimeout (async)
Ss @ lodash.js:6710
b @ lodash.js:10441
setTimeout (async)
Ss @ lodash.js:6710
b @ lodash.js:10441
setTimeout (async)
Ss @ lodash.js:6710
b @ lodash.js:10441
setTimeout (async)
Ss @ lodash.js:6710
v @ lodash.js:10409
k @ lodash.js:10478
input @ StoryContent.vue?8401:1
ie @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Qr.a._wrapper @ vue.runtime.esm.js:6961

```
