### ISSUE TITLE
Stories seem to be blank...

### ISSUE THREAD

**Issue by kiddinn** [google/timesketch#2224]
**Describe the bug**
I just deployed a new TS instance, uploaded some files/timelines and ran some analyzers, some of which generated stories, the stories are visible in the UI, but once I click on them, the page is completely empty...

Then I go into notebook, and I type...

```python
%timesketch_set_active_sketch 1
stories = timesketch_list_stories_func()
a_story = stories.get('Browser Artifacts - <NAME OF TIMELINE>')
```

Then I can easily do:

```python
a_story.title
```
And the title gets printed, BUT if I do

```python
a_story.to_markdown()
```

An error appears...

```
[2022-06-19 00:35:30,603] timesketch.app/ERROR Exception on /api/v1/sketches/1/stories/1/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/story.py", line 227, in post
    story=self._export_story(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/story.py", line 137, in _export_story
    exporter.from_string(story.content)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/stories/interface.py", line 61, in from_string
    self.from_block_dict(block)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/stories/interface.py", line 97, in from_block_dict
    "value": self._data_fetcher.get_aggregation_group(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/stories/api_fetcher.py", line 133, in get_aggregation_group
    aggregator_obj = agg_class(sketch_id=self._sketch_id, index=index)
TypeError: __init__() got an unexpected keyword argument 'index'
```

**Expected behavior**
I expected to be able to view a story, both in the UI and in the notebook/API client

**Screenshots**
This is how the "story" appears in the UI
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/8701947/174465912-c2a2cc37-6e04-41f9-91be-4c77612340e2.png">

**Comment by jaegeral** [comment]
Seems fixed now, closing it out, feel free to comment if the problem re-appears.
