### ISSUE TITLE
when sketch gets big, some timelines start to return error 500

### ISSUE THREAD

**Issue by arisjr** [google/timesketch#2353]
**Describe the bug**
I'm working in a case that has a lot of logs and it is the third time I have to recreate the timeketch data from zero to start all over again, every time I start to insert more logs it return error 500 (better explained bellow).

**To Reproduce**
The plaso timelines are four and somehow small, with less than 2M events. I have several JSONL timelines converted from custom syslog server log entries (generated from a syslog agent on windows servers mostly) and also several JSONL converted from Checkpoint Firewall log.export files. The JSONL timelines are 1.5GB average in size and have 3M events in average.

In my data ingestion process I do this: I insert the JSONL and plaso data through the web interface, and then I test the just inserted timeline on the explorer with searches with * and with asc and desc order. 

The first time I tried to insert all the data at once, but then, at some point, some of the timelines stopped working with error 500.
When I looked at the logs, opensearch says that "All Shards Failed". Looking more closely into opensearch, the cluster was red or yellow (It's been four weeks now from the first try, sorry the bad memory), with shards unassigned due to inability to create more replicas. So I putted replicas on 0, cause its a single node server anyway, then all the shards get assigned, the cluster returns to green, BUT the problem with the timelines remains: error 500 on the browser for some timelines, with "all shards failed" on opensearch, even with green cluster.  So I recreated the timesketch environment the first time. 

From that point on, I'm analyzing the day and the hour of the event, inserting logs just as needed, no full import. Things worked like a charm until the point I need to insert more data at some point. Same problem. There's no specific timelines that goes into error, sometimes is one that was perfectly working with no extra insertion of data. 

At the third try, I noticed that after inserting some JSONL timelines after the sketch is already big, in the overview pane, some timelines that were working (and no extra timeline added to it) simply stopped showing the number of events it has. It's a sign that things aren't working fine no more, and some timelines returning error 500 with "All shards failed" on opensearch log. So I looked at the cluster, it was yellow, shards unassigned due to lack of replicas, setted replicas to zero, cluster returns to green, but the problem remains: when I try to explore some timelines with *, error 500 with "all shards failed" even with cluster in green status (in perfect health). 
At this point in the sketch in the third try, we have 41 file imports (only four are plasos, the rest is JSONL files) on 21 timelines. 

At this last time, I even checked the index for errors with putting the opensearch docker down, running the bash on the opensearch docker, and then running the command java as follows: 
```
$ docker-compose stop opensearch
$ docker-compose run opensearch bash
[opensearch@12680a495233 ~]$ java -cp lucene-core*.jar -ea:org.apache.lucene... org.apache.lucene.index.CheckIndex /usr/share/opensearch/data/nodes/0/indices/9-MtQEkyTSefAIV_dKWH4A/0/index -verbose -exorcise
```
It checked the index and no error was found, and the problem remained. 

"9-MtQEkyTSefAIV_dKWH4A" is problematic index, that has 66374730 docs count and 30.2GB.

**Expected behavior**
When clicking on a Timeline on overview pane, it returns the the query * on the selected timeline on the explore view, with no 500 error.

**Desktop (please complete the following information):**
OS (server side): I'm using timesketch docker-compose as-is from the project, running Ubuntu 22.04 in a single 128GB RAM bi-processed dedicated machine (HP z820) as the analysis server, ~800GB SSD hard drive. The docker images are as follows:
``` 
us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:latest (created four weeks ago)
nginx:1.19.3-alpine
opensearchproject/opensearch:1.2.2
postgres:13.0-alpine
redis:6.0.8-alpine
```
OS (client side): Ubuntu 22.04
BROWSER: Chrome
VERSION: 105.0.5195.125 (Official Build) (64-bit)

**Comment by jaegeral** [comment]
Thx for the report.

I do not have an adhoc answer for your problem.

You say you have several hundred JSONL files with avg 1.5 GB. What is the number of events you see those errors occur (ca.)?

It is hard to triage the problem but the error messages you quote indicate that something is happening to your OpenSearch Instance after importing a certain amount of data.

Some things could you try:
- Use the API to import the data instead of the Web Uploader
- Filter the data before you import it to Timesketch, while it is made to scale pretty good, it might hit some limitations at some point
- Distribute your OpenSearch instance over multiple machines.
- Turn on more verbose logging in OpenSearch to troubleshoot when something is happening to your OpenSearch instance
- Split the data types over multiple sketches, while that defeats a little the purpose of TimeSketch, it might be a viable option (or split it by e.g. month so that you have all data types in one sketch for one month, then create a new one).
- Avoid Searches for `*` it is a very expensive operation, combine it with Timefilters to avoid those broad searches especially if your dataset is that broad.

Our posted numbers for size of Sketches are only rought estimations, but I hope my ideas can help a bit.

**Comment by jaegeral** [comment]
@arisjr any updates?

**Comment by arisjr** [comment]
Hi @jaegeral ,

I created again the timesketch environment from zero, and we are carefully re-uploading timelines for our final report here doing some steps you said - separating some of the data in different sketches. As soon we finish this urgent task that will not take long, I will reinsert the data as one sketch to reproduce the error with opensearch in verbose logging mode.

**Comment by arisjr** [comment]
@jaegeral In one sketch that I separated and done an input of ~60M events, it started to give all shards failed error on query with *.  So I started to narrow the results with datetime filter. When the query results are less then ~24M events, it works fine. When I do a wider filter, and the results goes above -24M events, then all shards failed error start to happen.

I even did a debug and trace log on the opensearch, but it gave me no hint on the problem. Perhaps for you guys it could be more meaningful. 


```
[2022-10-19T11:27:34,770][DEBUG][o.o.t.TaskCancellationService] [05c432f57fb9] Received ban for the parent [-6CTDQG0T4u6KcEI41K_0A:202] on the node [-6CTDQG0T4u6KcEI41K_0A], reason: [channel closed]
[2022-10-19T11:27:34,795][DEBUG][o.o.a.s.TransportSearchAction] [05c432f57fb9] [-6CTDQG0T4u6KcEI41K_0A][79e7492981884981a62cedcb6dd83499][0]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[79e7492981884981a62cedcb6dd83499], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=null, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"size":40,"query":{"bool":{"should":[{"bool":{"must":[{"query_string":{"query":"*","fields":[],"type":"best_fields","default_operator":"and","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}}],"must_not":[{"exists":{"field":"__ts_timeline_id","boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},{"bool":{"must":[{"query_string":{"query":"*","fields":[],"type":"best_fields","default_operator":"and","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},{"terms":{"__ts_timeline_id":[12],"boost":1.0}}],"filter":[{"exists":{"field":"__ts_timeline_id","boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"_source":{"includes":["message","datetime","timestamp","timestamp_desc","_index","__ts_timeline_id","message","comment","timesketch_label","tag","similarity_score","human_readable","__ts_emojis"],"excludes":[]},"sort":[{"datetime":{"order":"asc"}}],"aggregations":{"indices":{"terms":{"field":"_index","size":1,"min_doc_count":0,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]}},"timelines":{"terms":{"field":"__ts_timeline_id","size":1,"min_doc_count":0,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]}},"count_over_time":{"auto_date_histogram":{"field":"datetime","buckets":50,"minimum_interval":null}}}}, cancelAfterTimeInterval=null}] lastShard [true]
org.opensearch.transport.RemoteTransportException: [05c432f57fb9][172.21.0.3:9300][indices:data/read/search[phase/query]]
Caused by: org.opensearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
        at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:332) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:162) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:441) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:505) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.access$500(SearchService.java:154) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:474) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:71) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:57) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:792) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.2.2.jar:1.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.opensearch.tasks.TaskCancelledException: cancelled task with reason: channel closed
        at org.opensearch.search.query.QueryPhase.lambda$executeInternal$3(QueryPhase.java:297) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.ContextIndexSearcher$MutableQueryTimeout.checkCancelled(ContextIndexSearcher.java:401) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:67) ~[opensearch-1.2.2.jar:1.2.2]
        at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
        at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:253) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:226) ~[opensearch-1.2.2.jar:1.2.2]
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:443) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
        at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:359) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:308) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:162) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:441) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:505) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.access$500(SearchService.java:154) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:474) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:71) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:57) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:792) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) ~[opensearch-1.2.2.jar:1.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) ~[?:?]
[2022-10-19T11:27:34,796][DEBUG][o.o.a.s.TransportSearchAction] [05c432f57fb9] All shards failed for phase: [query]
org.opensearch.tasks.TaskCancelledException: cancelled task with reason: channel closed
        at org.opensearch.search.query.QueryPhase.lambda$executeInternal$3(QueryPhase.java:297) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.ContextIndexSearcher$MutableQueryTimeout.checkCancelled(ContextIndexSearcher.java:401) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:67) ~[opensearch-1.2.2.jar:1.2.2]
        at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
        at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:253) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:226) ~[opensearch-1.2.2.jar:1.2.2]
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:443) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
        at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:359) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:308) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:162) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:441) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:505) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.access$500(SearchService.java:154) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:474) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:71) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:57) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:792) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.2.2.jar:1.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[2022-10-19T11:27:34,797][DEBUG][o.o.t.TaskCancellationService] [05c432f57fb9] Removing ban for the parent [-6CTDQG0T4u6KcEI41K_0A:202] on the node [-6CTDQG0T4u6KcEI41K_0A]
[2022-10-19T11:27:34,797][WARN ][r.suppressed             ] [05c432f57fb9] path: /79e7492981884981a62cedcb6dd83499/_search, params: {index=79e7492981884981a62cedcb6dd83499, _source_includes=message,datetime,timestamp,timestamp_desc,_index,__ts_timeline_id,message,comment,timesketch_label,tag,similarity_score,human_readable,__ts_emojis, search_type=query_then_fetch}
org.opensearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:642) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:360) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:677) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:457) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:82) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:291) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:84) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:72) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:593) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.transport.TransportService$6.handleException(TransportService.java:742) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1357) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1466) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1440) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:74) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:69) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:65) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:101) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:57) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:792) [opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [opensearch-1.2.2.jar:1.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.opensearch.tasks.TaskCancelledException: cancelled task with reason: channel closed
        at org.opensearch.search.query.QueryPhase.lambda$executeInternal$3(QueryPhase.java:297) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.ContextIndexSearcher$MutableQueryTimeout.checkCancelled(ContextIndexSearcher.java:401) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:67) ~[opensearch-1.2.2.jar:1.2.2]
        at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
        at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:253) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:226) ~[opensearch-1.2.2.jar:1.2.2]
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:443) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
        at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:359) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:308) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:162) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:441) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:505) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService.access$500(SearchService.java:154) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:474) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:71) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86) ~[opensearch-1.2.2.jar:1.2.2]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) ~[opensearch-1.2.2.jar:1.2.2]
        ... 6 more

```

**Comment by Zawadidone** [comment]
@arisjr what was the size of the index and the amount of shards of the index?

I also encountered issues with Timesketch when uploading huge amount of data. I switched to using Logstash to upload data to Elasticsearch instead of using the longer route through Timesketch.

**Comment by Zawadidone** [comment]
Yes the numbers of shards could impact the performance of an index. There are a few resources available that explain how to create a strategy for this. https://opster.com/guides/elasticsearch/capacity-planning/elasticsearch-number-of-shards/, https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html

I have had a good experience with 30/50GB per shards for an index and a minum of 1 shard for every node.

Yes great results by using the feature in this commit (https://github.com/hnhdev/timesketch/commit/94ff9dfad04e25f0ad75c7f724b9007d7b347945) for which I will create a PR for timesketch later on. Logstash helps because data is directly uploaded to Elasticsearch instead of through Timesketch (Filesystem/Redis). 

https://github.com/hnhdev/timesketch/commit/94ff9dfad04e25f0ad75c7f724b9007d7b347945#diff-b3d771f614eff0127019c45588b6c127075259496111d7e85c2d73ad1bdc3b30R290

**Comment by jaegeral** [comment]
Hm searching for * on over 24 mil events does not sound helpful, we are trying to improve the user flow to reduce the haystack right from the beginning, either by focusing on a specific time or starting with a term.

I am not sure if we can solve the problem of hitting OpenSearch Limits.

**Comment by arisjr** [comment]
> Hm searching for * on over 24 mil events does not sound helpful, we are trying to improve the user flow to reduce the haystack right from the beginning, either by focusing on a specific time or starting with a term.
> 
> I am not sure if we can solve the problem of hitting OpenSearch Limits.

Hello, @jaegeral 

The solution adopted in the most recent releases of timesketch are quite elegant and efficient to circumvent the problem. The need to add a time frame and a search term had eliminated the big timelines adding problem. 
I think neither opensearch-dashboard nor elastic kibana enables searches without a time frame...
