### ISSUE TITLE
Export failure (opensearch error) - Trying to create too many scroll contexts

### ISSUE THREAD

**Issue by Xboarder56** [google/timesketch#2364]
**Describe the bug**
Attempting to export a sketch returns the following opensearch error. 

`Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting.`

**To Reproduce**
1. Create a sketch with a large story and attempt to export. 

**Expected behavior**
Sketch would successfully export.

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser: chrome
 - Version: 105.0.5195.125 (Official Build) (x86_64) 

**Additional context**
[2022-10-10 22:49:22,692] timesketch.app/ERROR Exception on /api/v1/sketches/1/archive/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 156, in post
    return self._export_sketch(sketch)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 316, in _export_sketch
    self._export_view(view, sketch, zip_file)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/archive.py", line 365, in _export_view
    result = self.datastore.search(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/datastores/opensearch.py", line 538, in search
    return self.client.search(
  File "/usr/local/lib/python3.8/dist-packages/opensearchpy/client/utils.py", line 177, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/opensearchpy/client/__init__.py", line 1593, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/opensearchpy/transport.py", line 412, in perform_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/opensearchpy/transport.py", line 373, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/opensearchpy/connection/http_urllib3.py", line 282, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/opensearchpy/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.TransportError: TransportError(429, 'search_phase_execution_exception', 'Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting.')

**Comment by jaegeral** [comment]
duplicate to https://github.com/google/timesketch/issues/2344
