### ISSUE TITLE
Can't import plaso file in timesketch: raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

### ISSUE THREAD

**Issue by juju4** [google/timesketch#239]
Hello,

when importing into timesketch, got
```
# psort.py -d --logfile /tmp/victoria-v8.sda1-psort2.log -o timesketch /tmp/victoria-v8.sda1.img.zip.plaso
Missing parameter timeline_name for output module: test
> /usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py(113)_raise_error()
-> raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
(Pdb)
# tail /tmp/victoria-v8.sda1-psort2.log
[INFO] Timeline name: 
[INFO] Index: 8ecd8babe5b843958c35d9e483eee72b
[INFO] Timeline name: test

[DEBUG] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
[INFO] Starting new HTTP connection (1): 127.0.0.1
[DEBUG] "HEAD /8ecd8babe5b843958c35d9e483eee72b HTTP/1.1" 404 0
[DEBUG] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
[DEBUG] "PUT /8ecd8babe5b843958c35d9e483eee72b HTTP/1.1" 400 478
[ERROR] TransportError(400, u'mapper_parsing_exception', u'Mapping definition for [_timestamp] has unsupported parameters:  [path : datetime]')
```

My timesketch setup is done with the following ansible role
https://github.com/juju4/ansible-timesketch

Test is done with packaged plaso so it is 1.4.0 for both trusty (ppa gift) and xenial (ubuntu).
Gave a quick try to 1.5.0 but have missing modules
```
~/plaso-1.5.0# /usr/local/bin/psort.py --version
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.5.0', 'psort.py')
[...]
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.0-py2.7.egg/plaso/parsers/winprefetch.py", line 4, in <module>
    import pyscca
ImportError: No module named pyscca
```
and pyssca is not found either in xenial or pip.

Thanks

**Comment by berggren** [comment]
Hi,

Yes this error is due to incompatibility with Plaso 1.4.x. The elastic
mapping changed between 1.4 and 1.5 to be able to support elastic 2.x.

The missing packages should be in the GIFT ppa.

Let me know if you have any problem installing the dependencies.

/jbn

**Comment by juju4** [comment]
It seems to be ok for dependency but got another error. closing this one
