### ISSUE TITLE
drop-db issue

### ISSUE THREAD

**Issue by michael2425** [google/timesketch#2432]
Unable to drop database in timesketch-web instance using "drop-db" command. Error shown as below:

```
Do you really want to drop all the database tables? [y/N]: y
Are you REALLLY sure you want to DROP ALL the database tables? [y/N]: y
All tables dropped. Database is now empty.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table investigativequestion because other objects depend on it
DETAIL:  constraint investigativequestion_searchtempl_investigativequestion_id_fkey on table investigativequestion_searchtemplate depends on table investigativequestion
constraint investigativequestion_sigmarule_investigativequestion_id_fkey on table investigativequestion_sigmarule depends on table investigativequestion
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 445, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/timesketch/tsctl.py", line 170, in drop_db
    drop_all()
  File "/usr/local/lib/python3.10/dist-packages/timesketch/models/__init__.py", line 63, in drop_all
    BaseModel.metadata.drop_all(bind=engine)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/schema.py", line 4341, in drop_all
    bind._run_visitor(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2049, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1618, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/ddl.py", line 948, in visit_metadata
    self.traverse_single(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/ddl.py", line 1002, in visit_table
    self.connection.execute(DropTable(table))
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1039, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table investigativequestion because other objects depend on it
DETAIL:  constraint investigativequestion_searchtempl_investigativequestion_id_fkey on table investigativequestion_searchtemplate depends on table investigativequestion
constraint investigativequestion_sigmarule_investigativequestion_id_fkey on table investigativequestion_sigmarule depends on table investigativequestion
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL:
DROP TABLE investigativequestion]
(Background on this error at: http://sqlalche.me/e/2j85)

```

**Comment by jaegeral** [comment]
@berggren is it possible that we need to change this line:
https://github.com/google/timesketch/blob/db986692f1f73614290ba9116f0d28d6b1c01062/timesketch/models/__init__.py#L63
```
    BaseModel.metadata.drop_all(bind=engine)
```

to:
```
BaseModel.metadata.drop_all(bind=engine, cascade=True)
```

This updated version of the drop_all function will drop all the tables and dependent objects in the database, and will empty the database. Please note that this operation is irreversible, and it will permanently delete all the data in the database. You should only use this function if you are sure you want to delete all the data in the database, and if you have backups of the data in case you need to restore it.

**Comment by jaegeral** [comment]
I could not verify that problem, so closing it out, if it re-occurs, please speak up.
