### ISSUE TITLE
Failed to upgrade data base -> column "group_id" of relation "searchindex_accesscontrolentry" already exists

### ISSUE THREAD

**Issue by Xboarder56** [google/timesketch#2463]
**Describe the bug**
Attempting a upgrade fails when upgrading the database.

**Additional context**

root@container_id:/timesketch/timesketch# tsctl db current
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
root@container_id:/timesketch/timesketch# tsctl db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> be32626451fb, Add ACL relationships
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateColumn: column "group_id" of relation "searchindex_accesscontrolentry" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 445, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/timesketch/timesketch/migrations/env.py", line 98, in <module>
    run_migrations_online()
  File "/timesketch/timesketch/migrations/env.py", line 90, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/timesketch/timesketch/migrations/versions/be32626451fb_.py", line 22, in upgrade
    op.add_column(
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/ops.py", line 1906, in add_column
    return operations.invoke(op)
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/toimpl.py", line 131, in add_column
    operations.impl.add_column(table_name, column, schema=schema)
  File "/usr/local/lib/python3.8/dist-packages/alembic/ddl/impl.py", line 231, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.8/dist-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1039, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateColumn) column "group_id" of relation "searchindex_accesscontrolentry" already exists

[SQL: ALTER TABLE searchindex_accesscontrolentry ADD COLUMN group_id INTEGER]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by jaegeral** [comment]
Hm is it possible that you already tried to update? Does the issue still exist?

**Comment by Xboarder56** [comment]
@jaegeral so I got it to work after cloning again recently but the upgrade never seems to work. I followed the steps in the upgrade documents from here: https://timesketch.org/guides/admin/upgrade/

However after they complete and I launch the containers backup I get the following table error.

```
Attaching to postgres
postgres                 |
postgres                 | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres                 |
postgres                 | 2023-04-11 19:53:01.758 UTC [1] LOG:  starting PostgreSQL 13.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
postgres                 | 2023-04-11 19:53:01.758 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres                 | 2023-04-11 19:53:01.759 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres                 | 2023-04-11 19:53:01.764 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres                 | 2023-04-11 19:53:01.770 UTC [21] LOG:  database system was shut down at 2023-04-11 19:52:38 UTC
postgres                 | 2023-04-11 19:53:01.780 UTC [1] LOG:  database system is ready to accept connections
postgres                 | 2023-04-11 19:53:56.570 UTC [35] ERROR:  column view.searchtemplate_json does not exist at character 276
postgres                 | 2023-04-11 19:53:56.570 UTC [35] STATEMENT:  SELECT view.id AS view_id, view.created_at AS view_created_at, view.updated_at AS view_updated_at, view.name AS view_name, view.description AS view_description, view.query_string AS view_query_string, view.query_filter AS view_query_filter, view.query_dsl AS view_query_dsl, view.searchtemplate_json AS view_searchtemplate_json, view.user_id AS view_user_id, view.sketch_id AS view_sketch_id, view.searchtemplate_id AS view_searchtemplate_id
postgres                 |      FROM view
postgres                 |      WHERE 1 = view.user_id AND view.name = '' ORDER BY view.updated_at DESC
postgres                 |       LIMIT 10
```

**Comment by Xboarder56** [comment]
Inspecting the view table I don't even see this column at all on the latest a3b082c9e6e9 tag. I ran the steps to stamp the database to this and reboot the container but still no luck when inspecting it. 

![image](https://user-images.githubusercontent.com/967563/231282772-3b8fbbeb-d779-4793-8e55-34e2f4a16c44.png)

**Comment by Xboarder56** [comment]
When I ran tsctl db current on the reverted snapshot it showed just 2 messages which I believe indicates no db upgrade is needed? But that missing column still isn't showing correctly for revision a3b082c9e6e9.  

```
root@1ba9b79b111b:/tmp/timesketch/timesketch# tsctl db current
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
root@1ba9b79b111b:/tmp/timesketch/timesketch#
```

**Comment by Xboarder56** [comment]
Reviewing this migration file further (https://github.com/google/timesketch/blob/master/timesketch/migrations/versions/a3b082c9e6e9_extend_searchtemplate.py) I'm pretty positive I'm stuck on schema -> 180a387da650

I'm missing all the columns from that schema file and following the upgrade instructions:
tsctl db current
tsctl db history
tsctl db stamp 180a387da650
tsctl db upgrade 

just refuses to add the missing columns to the tables. Thus breaking the containers when I do a pull.
