### ISSUE TITLE
docker dev errors

### ISSUE THREAD

**Issue by eljeffeg** [google/timesketch#2468]
Ran `docker compose up` on the `docker/dev` and got these errros on the dev-timesketch.  It appears some files were not copied in a python `flask_script` requirement is not met.  Or the dev image hasn't been updated in some time.

```sh
dev-timesketch-1     | cp: cannot stat '/usr/local/src/timesketch/data/intelligence_tag_metadata.yaml': No such file or directory
dev-timesketch-1     | cp: cannot stat '/usr/local/src/timesketch/data/generic.mappings': No such file or directory
dev-timesketch-1     | cp: cannot stat '/usr/local/src/timesketch/data/data_finder.yaml': No such file or directory
dev-timesketch-1     | cp: cannot stat '/usr/local/src/timesketch/data/bigquery_matcher.yaml': No such file or directorydev-timesketch-1     | Please pass values for the ELASTIC_ADDRESS and ELASTIC_PORT environment variables
dev-timesketch-1     | Traceback (most recent call last):
dev-timesketch-1     |   File "/usr/local/bin/tsctl", line 33, in <module>
dev-timesketch-1     |     sys.exit(load_entry_point('timesketch', 'console_scripts', 'tsctl')())
dev-timesketch-1     |   File "/usr/local/bin/tsctl", line 25, in importlib_load_entry_point
dev-timesketch-1     |     return next(matches).load()
dev-timesketch-1     |   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
dev-timesketch-1     |     module = import_module(match.group('module'))
dev-timesketch-1     |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
dev-timesketch-1     |     return _bootstrap._gcd_import(name[level:], package, level)
dev-timesketch-1     |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
dev-timesketch-1     |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
dev-timesketch-1     |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
dev-timesketch-1     |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
dev-timesketch-1     |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
dev-timesketch-1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
dev-timesketch-1     |   File "/usr/local/src/timesketch/timesketch/tsctl.py", line 27, in <module>
dev-timesketch-1     |     from flask_script import Command
dev-timesketch-1     | ModuleNotFoundError: No module named 'flask_script'
dev-timesketch-1     | Timesketch development server is ready!
```

**Comment by eljeffeg** [comment]
I was running the release version, which was a year old.  Downloading the direct source and changing  the docker-compose to build resolved the issue.
```
    build:
      context: ../../
      dockerfile: ./docker/dev/build/Dockerfile
```

**Comment by eljeffeg** [comment]
Even running this from inside the timesketch-dev container produces a connection refused.
```
# curl http://localhost:8080
curl: (7) Failed to connect to localhost port 8080 after 0 ms: Connection refused
```

**Comment by eljeffeg** [comment]
I was trying to build timesketch on Windows.  I eventually gave up and just installed WSL and followed the instructions for a linux build.  It would be nice to get the dev stuff working though and pointed to the build.. as I'd like to integrate `hayabusa` zip/evtx.
