### ISSUE TITLE
[frontend-ng] blank sketch throws error

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2649]
**Describe the bug**
In the new v2UI (frontened-ng), when creating a new blank sketch the following error is raised:
```
TypeError: Cannot read properties of undefined (reading '$el')
    at o.setDrawerBorderStyle (Sketch.vue:392:1)
    at o.<anonymous> (Sketch.vue:333:14)
[...]
```

**To Reproduce**
1. Go to the new v2Ui
2. Open the developer console
3. Create a new sketch
4. When you are on the "It's empty around here" page, you should get the TypeError mentioned above

**Additional context**
The error does not seem to impact the functionality of Timesketch much.

**Comment by jaegeral** [comment]
I put it in the bugfix milestone for Q2, but not blocking our main change soonish.
