### ISSUE TITLE
Analyzer UI error

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2738]
**Describe the bug**
With existing analyzers the new Analyzer UI might throw the following (non blocking) error:
```
TypeError: Cannot read properties of undefined (reading 'description')
    at o.updateAnalyzerResultsData (AnalyzerResults.vue:186:1)
    at o.<anonymous> (AnalyzerResults.vue:174:1)
    at h (runtime.js:64:40)
    at Generator.<anonymous> (runtime.js:299:22)
    at Generator.next (runtime.js:124:21)
    at a (asyncToGenerator.js:4:20)
    at s (asyncToGenerator.js:23:9)
    at x.mb (app_bundle.js:29:385)
    at p.ya (app_bundle.js:23:249)
    at app_bundle.js:63:342
    at x.gf (app_bundle.js:30:229)
    at p.Oh (app_bundle.js:24:302)
    at g (app_bundle.js:20:381)
```

TODO: Check if `description` exists before trying to assign it. [code here](https://github.com/google/timesketch/blob/master/timesketch/frontend-ng/src/components/LeftPanel/AnalyzerResults.vue#L186)

**Comment by jkppr** [comment]
I cannot reproduce this bug in my dev environment. It only triggers sometime in the prod deployment, but never in my dev :( This makes it a bit harder to debug. However, here is my attempt:

Affected code:
```JavaScript
perAnalyzer[session.analyzer_name] = {
              timelines: {},
              analyzerInfo: {
                name: session.analyzer_name,
                description: this.analyzerList[session.analyzer_name].description,
                is_multi: this.analyzerList[session.analyzer_name].is_multi,
                display_name: this.analyzerList[session.analyzer_name].display_name,
              },
            }
```

It looks like the `this.analyzerList[session.analyzer_name]` does not return always an analyzer and can be undefined in some edge cases (unclear which edge cases though). Based on the code it should cover all available analyzers and it shouldn't be possible for an analyzer to be missing.

Fix:
Based on this assumption I introduced a fallback to the analyzer short name only, if the analyzer is missing from the list. This will prevent breaking errors in the frontend when the edge case occurs and also allows for a better debugging.

I'll Keep this issue open to further investigate and find a more refined solution.
