### ISSUE TITLE
NULL byte error when using csv2ts

### ISSUE THREAD

**Issue by BannersSecret** [google/timesketch#274]
Hi,

I've recently put together a simple bash script which manipulates the csv output from Plaso 1.4 into a format that can be used with csv2ts. The conversion seems to work perfectly (extensively tested on timelines pulled from a system), and I've been able to process a lot of timelines and import them into Timesketch. Unfortunately this morning I've begun processing timelines from other systems, and am getting a 50% success rate, with the failures providing this error:

Traceback (most recent call last):
 File "/home/timesketch/timesketch/tsctl", line 385, in <module>
   shell_manager.run()
 File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
   result = self.handle(sys.argv[0], sys.argv[1:])
 File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
   res = handle(*args, **config)
 File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
   return self.run(*args, **kwargs)
 File "/home/timesketch/timesketch/tsctl", line 355, in run
   for event in read_and_validate_csv(file_path):
 File "/home/timesketch/timesketch/timesketch/lib/utils.py", line 57, in read_and_validate_csv
   for row in reader:
 File "/usr/lib/python2.7/csv.py", line 108, in next
   row = self.reader.next()
_csv.Error: line contains NULL byte

I've searched for empty lines/columns in the files I'm importing into Timesketch (grepping for ,,) but am not getting any hits. I've also narrowed down to 1,000 events on one timeline (manual-style....noting down the last event number (to the nearest 1,000) and then going by eye over the CSV looking for any issues) but I can't identify what might be kicking this out.

Any thoughts?

A

**Comment by BannersSecret** [comment]
BTW, I know there is a psort output switch for timesketch, however I was only provided with a pile of CSVs from others, so needed to come up with a way of converting them.

**Comment by berggren** [comment]
This can be solved by removing the NUL bytes from the file prior to ingesting.

$ cat timeline.csv | tr -d '\0' > timeline_new.csv

Verified with the reporter that this solved the problem.
