### ISSUE TITLE
cannot run Hashr analayzer

### ISSUE THREAD

**Issue by hasamba** [google/timesketch#2807]
**Describe the bug**
hashr does not work

**To Reproduce**
run Hashr analyzer

**Screenshots**
![image](https://github.com/google/timesketch/assets/7392290/78620e67-7623-4520-8556-4a70906d31eb)

**Additional context**
Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/timesketch/lib/analyzers/interface.py", line 1173, in run_wrapper result = self.run() File "/usr/local/lib/python3.10/dist-packages/timesketch/lib/analyzers/hashr_lookup.py", line 306, in run matching_hashes = self.check_against_hashr(list(hash_events_dict.keys())) File "/usr/local/lib/python3.10/dist-packages/timesketch/lib/analyzers/hashr_lookup.py", line 149, in check_against_hashr samples_table = meta_data.tables["samples"] KeyError: 'samples'

**Comment by hasamba** [comment]
hi @jkppr 
it seems the db is empty, im sorry but i didnt understood that i have to run something before,
i just created the db and user, uncomment it in timesketch config...
i thought that timesketch will fill the db for me.
now i understand that i needed to install hashr

sorry

**Comment by jkppr** [comment]
You can build your own hashR database using this project: https://github.com/google/hashr
The database that is created using hashR is then compatible with the hashR analyzer for lookups. 

I'll try to catch that error and make it more obvious for future users :)
