### ISSUE TITLE
tagger analyzer bug

### ISSUE THREAD

**Issue by jkppr** [google/timesketch#2908]
**Describe the bug**
I noticed the following errors in the worker logs related to the tagger analyzer:

```
[2023-08-21 05:25:53,781] timesketch.tasks/INFO [tagger] result: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/timesketch/lib/analyzers/interface.py", line 1173, in run_wrapper
    result = self.run()
  File "/usr/local/lib/python3.10/dist-packages/timesketch/lib/analyzers/tagger.py", line 44, in run
    return self.tagger(self._tag_name, self._tag_config)
  File "/usr/local/lib/python3.10/dist-packages/timesketch/lib/analyzers/tagger.py", line 129, in tagger
    tag_value = self.MODIFIERS[mod](tag_value)
  File "/usr/local/lib/python3.10/dist-packages/timesketch/lib/analyzers/tagger.py", line 23, in <lambda>
    MODIFIERS = {"split": lambda x: x.split(), "upper": lambda x: x.upper()}
AttributeError: 'list' object has no attribute 'split'
```

**To Reproduce**
Still needs to be reproduced.

**Comment by jkppr** [comment]
Can be reproduced when using a sketch with an `yara_match` attribute. This happened to be a string in the past but can now also be a list already. Therefore it is not necessary to split the list anymore. Fix in #2935
