### ISSUE TITLE
version issue will not import plaso (2022)

### ISSUE THREAD

**Issue by gunner4361** [google/timesketch#2921]
Traceback (most recent call last):
  File "/usr/bin/pinfo.py", line 85, in <module>
    if not Main():
  File "/usr/bin/pinfo.py", line 62, in Main
    tool.PrintStorageInformation()
  File "/usr/lib/python3/dist-packages/plaso/cli/pinfo_tool.py", line 1681, in PrintStorageInformation
    storage_reader = self._GetStorageReader(self._storage_file_path)
  File "/usr/lib/python3/dist-packages/plaso/cli/pinfo_tool.py", line 587, in _GetStorageReader
    storage_factory.StorageFactory.CreateStorageReaderForFile(path))
  File "/usr/lib/python3/dist-packages/plaso/storage/factory.py", line 49, in CreateStorageReaderForFile
    return sqlite_reader.SQLiteStorageFileReader(path)
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/reader.py", line 20, in __init__
    self._store.Open(path=path)
  File "/usr/lib/python3/dist-packages/acstore/sqlite_store.py", line 1084, in Open
    self._ReadAndCheckStorageMetadata(check_readable_only=True)
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 212, in _ReadAndCheckStorageMetadata
    self._CheckStorageMetadata(
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 61, in _CheckStorageMetadata
    super(SQLiteStorageFile, self)._CheckStorageMetadata(
  File "/usr/lib/python3/dist-packages/acstore/sqlite_store.py", line 290, in _CheckStorageMetadata
    raise IOError((
OSError: Format version: 20220716 is too old and can no longer be read, minimum supported version: 20221023.

**Comment by jaegeral** [comment]
Based on the trace it seems you created the Plaso file with a very old Plaso version (2022) and your plaso in Timesketch also seems to be very old (2022).

Please see the plaso section on https://timesketch.org/guides/admin/troubleshooting/

**Comment by gunner4361** [comment]
I installed programs with the following, If there is a better way please
let me know, and thank you for your help.


The Log2timeline is current install

sudo add-apt-repository ppa:gift/stable

Update and install Plaso:

sudo apt-get update

sudo apt-get install plaso-tools

And timesketch is current Docker

Install Docker

sudo apt-get install docker-ce docker-ce-cli containerd.io
docker-buildx-plugin docker-compose-plugin

TEST

sudo docker run hello-world

TIMESKETCHcurl -s -O
https://raw.githubusercontent.com/google/timesketch/master/contrib/deploy_timesketch.sh

**Comment by jaegeral** [comment]
Again please follow the steps in the troubleshooting guide and provide the outputs of the commands asked.

We had many issues of people stating "used the recent version of x" and when checking it was not.

Thank you

**Comment by gunner4361** [comment]
pinfo.py -V
plaso - pinfo version 20230717

# psort.py --version
plaso - psort version 20230717

**Comment by jaegeral** [comment]
And where did you run those commands?

Also please provide info of `pinfo.py $FILENAME` of the file that failed to be uploaded.

**Comment by jaegeral** [comment]
Closing it out for now, if more information is provided we can re-open
