### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by migr19** [google/timesketch#3204]
Fresh deployed instance, after importing a timeline and execution of "timesketch analyze list" i get:
```
  RuntimeError: Failed to get a valid response json from Timesketch API, with error [504] Gateway Time-out <html>

  <head><title>504 Gateway Time-out</title></head>
  <body>
  <center><h1>504 Gateway Time-out</h1></center>
  <hr><center>nginx/1.25.5</center>
  </body>
  </html>
```

In the log file wsgi_error.log i found the following:
```
timesketch.app/ERROR Exception on /api/v1/sketches/46/analyzer/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/timesketch/api/v1/resources/analysis.py", line 311, in post
    analyzer_group, session = tasks.build_sketch_analysis_pipeline(
  File "/usr/local/lib/python3.10/dist-packages/timesketch/lib/tasks.py", line 478, in build_sketch_analysis_pipeline
    json.dumps(kwargs_list, sort_keys=True).encode("utf-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2024-10-15 18:05:39,624] timesketch.analyzers.hashlookup/ERROR Hashlookup conf not found
```

Any ideas how to fix it?

**Comment by migr19** [comment]
There was an error with some imported Sigma Rules -after deleting all rules it works

**Comment by jkppr** [comment]
@migr19 just to confirm, the imported Sigma Rules were custom rules you imported or rules we ship with the repository?
