### ISSUE TITLE
psycopg2.Internal error

### ISSUE THREAD

**Issue by owllie90** [google/timesketch#321]
Hi, 

I am receiving this error when i tried to login to timesketch via the portal.

InternalError: (psycopg2.InternalError) current transaction is aborted, commands ignored until end of transaction block
 [SQL: 'SELECT "user".id AS user_id, "user".created_at AS user_created_at, "user".updated_at AS user_updated_at, "user".username AS user_username, "user".password AS user_password, "user".name AS user_name, "user".email AS user_email, "user".active AS user_active \nFROM "user" \nWHERE "user".id = %(param_1)s'] [parameters: {'param_1': u'1'}]
127.0.0.1 - - [23/May/2017 10:39:29] "GET / HTTP/1.1" 500 -

**Comment by berggren** [comment]
Hi,
Did you configure your postgresql server? Does the username match the one you have configured in /etc/timesketch.conf?

**Comment by owllie90** [comment]
Yes. i did configured. now i am facing the below error:

sansforensics@siftworkstation:/mnt/hgfs/H/20170601-03-ssg-mw/bct-apps-int-uat/bct-apps-int-uat-cd-hdd$ sudo tsctl runserver -h 0.0.0.0 -p 5000
/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py:163: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  CsrfProtect(app)
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [13/Jun/2017 09:26:48] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [13/Jun/2017 09:26:48] "GET /login/?next=%2F HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2017 09:26:48] "GET /static/third_party/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2017 09:26:48] "GET /static/css/timesketch.css HTTP/1.1" 404 -
127.0.0.1 - - [13/Jun/2017 09:26:48] "GET /static/img/logo.png HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2017 09:26:48] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [13/Jun/2017 09:27:01] "POST /login/?next=%2F HTTP/1.1" 302 -
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/default_comparator.py:161: SAWarning: The IN-predicate on "sketch_accesscontrolentry.group_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  'strategies for improved performance.' % expr)
[2017-06-13 09:27:01,456] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/ui/views/home.py", line 55, in home
    View.updated_at.desc()).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) column view.query_dsl does not exist
LINE 1: ...y_string, view.query_filter AS view_query_filter, view.query...
                                                             ^
 [SQL: 'SELECT view.id AS view_id, view.created_at AS view_created_at, view.updated_at AS view_updated_at, view.name AS view_name, view.query_string AS view_query_string, view.query_filter AS view_query_filter, view.query_dsl AS view_query_dsl, view.user_id AS view_user_id, view.sketch_id AS view_sketch_id, view.searchtemplate_id AS view_searchtemplate_id \nFROM view \nWHERE %(param_1)s = view.user_id AND view.name = %(name_1)s ORDER BY view.updated_at DESC \n LIMIT %(param_2)s'] [parameters: {'name_1': u'', 'param_1': 3, 'param_2': 1}]
127.0.0.1 - - [13/Jun/2017 09:27:01] "GET / HTTP/1.1" 500 -

**Comment by owllie90** [comment]
any updates? thanks.

**Comment by berggren** [comment]
This looks like an old bug. What version of Timesketch are you running? This should have been fixed already.

**Comment by berggren** [comment]
No response in 2.5 years, closing out.
