### ISSUE TITLE
Accesing a timeline created with CSV raises ConnectionError

### ISSUE THREAD

**Issue by sch3m4** [google/timesketch#369]
Hi, 
I'm using the last release (20170721) and I cannot access to a timeline created by uploading a CSV file, it shows the following exception:
PD: The CSV follows your guidelines from the Wiki page https://github.com/google/timesketch/wiki/UserGuideTimelineFromFile

timesketch_1     | 172.26.0.1 - - [21/Jul/2017 19:22:01] "GET /api/v1/sketches/1/views/1/ HTTP/1.1" 200 -
timesketch_1     | [2017-07-21 19:22:03,066] ERROR in app: Exception on /api/v1/sketches/1/explore/ [POST]
timesketch_1     | Traceback (most recent call last):
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
timesketch_1     |     rv = self.dispatch_request()
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
timesketch_1     |     return self.view_functions[rule.endpoint](**req.view_args)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
timesketch_1     |     resp = resource(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
timesketch_1     |     return self.dispatch_request(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
timesketch_1     |     resp = meth(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
timesketch_1     |     return func(*args, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 641, in post
timesketch_1     |     enable_scroll=False)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/datastores/elastic.py", line 273, in search
timesketch_1     |     scroll=scroll_timeout)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
timesketch_1     |     return func(*args, params=params, **kwargs)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 623, in search
timesketch_1     |     doc_type, '_search'), params=params, body=body)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 312, in perform_request
timesketch_1     |     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
timesketch_1     |   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 123, in perform_request
timesketch_1     |     raise ConnectionError('N/A', str(e), e)
timesketch_1     | ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f71f4ec9790>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f71f4ec9790>: Failed to establish a new connection: [Errno -2] Name or service not known)

**Comment by berggren** [comment]
Hi, this looks like Elasticsearch is not running. Have you started the server?

**Comment by ilyaglow** [comment]
Hi, it seems you are using docker, and this is a [well known](https://github.com/google/timesketch/issues/361) [issue](https://github.com/google/timesketch/issues/330) that can be fixed by changing `ELASTIC_ADDRESS=elastic` environment variable in the `docker-compose.yml`  to `ELASTIC_ADDRESS=elasticsearch`.

Actually the vagrant support here is more robust, but if you really want to use docker just like me you can check out [PR I sent recently](https://github.com/google/timesketch/pull/368) or [the dedicated repo](https://github.com/ilyaglow/docker-timesketch).

**Comment by sch3m4** [comment]
I've changed ELASTIC_ADDRESS to the correct service name as @ilyaglow said, but the timeline is not indexed. This time it results in the following error, and no events indexed:

timesketch_1     | 172.26.0.1 - - [22/Jul/2017 21:23:14] "POST /login/?next=%2F HTTP/1.1" 302 -
timesketch_1     | /usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/default_comparator.py:161: SAWarning: The IN-predicate on "sketch_accesscontrolentry.group_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
timesketch_1     |   'strategies for improved performance.' % expr)
timesketch_1     | 172.26.0.1 - - [22/Jul/2017 21:23:15] "GET / HTTP/1.1" 200 -
timesketch_1     | /usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py:1424: SAWarning: Got None for value of column sketch.id; this is unsupported for a relationship comparison and will not currently produce an IS comparison (but may in a future release)
timesketch_1     |   "(but may in a future release)" % column)

I'll give it a try to the docker repo.

**Comment by sch3m4** [comment]
My fault, everything works quite well!
