### ISSUE TITLE
Leaking database connections

### ISSUE THREAD

**Issue by bkvaluemeal** [google/timesketch#373]
Periodically Timesketch will fail and generate an error saying that it needs to roll back an invalid transaction to the database. Every HTTP request to the site after this point returns a 500. I have watches configured to automatically restart Timesketch when this happens (which appears to fix the problem), but over time there are 50+ accumulated open connections to my database. Is there any available workaround or fix to solve this problem, or did I misconfigure something?

I'm running:

- Timesketch==2016.11
- Elasticsearch==2.4.3
- Postgres==9.6.2
- cent_os==7.3.1611

This is the log output that I see:

```
Aug  2 01:56:47 timesketch1 timesketch: 172.16.0.40 - - [02/Aug/2017 01:56:47] "GET /login/?next=%2F HTTP/1.1" 500 -                                                                                  
Aug  2 01:57:17 timesketch1 timesketch: 172.16.0.40 - - [02/Aug/2017 01:57:17] "GET / HTTP/1.1" 302 -                                                                                                 
Aug  2 01:57:17 timesketch1 timesketch: [2017-08-02 01:57:17,078] ERROR in app: Exception on /login/ [GET]                                                                                            
Aug  2 01:57:17 timesketch1 timesketch: Traceback (most recent call last):                                                                                                                            
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app                                                                                  
Aug  2 01:57:17 timesketch1 timesketch: response = self.full_dispatch_request()                                                                                                                       
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request                                                                     
Aug  2 01:57:17 timesketch1 timesketch: rv = self.handle_user_exception(e)                                                                                                                            
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router                                                                  
Aug  2 01:57:17 timesketch1 timesketch: return original_handler(e)                                                                                                                                    
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception                                                                     
Aug  2 01:57:17 timesketch1 timesketch: reraise(exc_type, exc_value, tb)                                                                                                                              
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request                                                                     
Aug  2 01:57:17 timesketch1 timesketch: rv = self.dispatch_request()                                                                                                                                  
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request                                                                          
Aug  2 01:57:17 timesketch1 timesketch: return self.view_functions[rule.endpoint](**req.view_args)                                                                                                    
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/timesketch/ui/views/user.py", line 93, in login                                                                        
Aug  2 01:57:17 timesketch1 timesketch: user = User.query.filter_by(username=form.username.data).first()                                                                                              
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2755, in first                                                                          
Aug  2 01:57:17 timesketch1 timesketch: ret = list(self[0:1])                                                                                                                                         
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__                                                                    
Aug  2 01:57:17 timesketch1 timesketch: return list(res)                                                                                                                                              
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__                                                                       
Aug  2 01:57:17 timesketch1 timesketch: return self._execute_and_instances(context)                                                                                                                   
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances                                                         
Aug  2 01:57:17 timesketch1 timesketch: result = conn.execute(querycontext.statement, self._params)                                                                                                   
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute                                                                       
Aug  2 01:57:17 timesketch1 timesketch: return meth(self, multiparams, params)                                                                                                                        
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection                                                       
Aug  2 01:57:17 timesketch1 timesketch: return connection._execute_clauseelement(self, multiparams, params)                                                                                           
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement                                                       
Aug  2 01:57:17 timesketch1 timesketch: compiled_sql, distilled_params                                                                                                                                
Aug  2 01:57:17 timesketch1 consul[2683]: agent: Check 'service:timesketch' is now critical                                                                                                           
Aug  2 01:57:17 timesketch1 consul: 2017/08/02 01:57:17 [WARN] agent: Check 'service:timesketch' is now critical                                                                                      
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context                                                             
Aug  2 01:57:17 timesketch1 timesketch: None, None)                                                                                                                                                   
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception                                                      
Aug  2 01:57:17 timesketch1 timesketch: exc_info                                                                                                                                                      
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause                                                              
Aug  2 01:57:17 timesketch1 timesketch: reraise(type(exception), exception, tb=exc_tb, cause=cause)                                                                                                   
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context                                                             
Aug  2 01:57:17 timesketch1 timesketch: conn = self._revalidate_connection()                                                                                                                          
Aug  2 01:57:17 timesketch1 timesketch: File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection                                                        
Aug  2 01:57:17 timesketch1 timesketch: "Can't reconnect until invalid "                                                                                                                              
Aug  2 01:57:17 timesketch1 timesketch: StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'SELECT "user".id AS user_id, "user".crea
ted_at AS user_created_at, "user".updated_at AS user_updated_at, "user".username AS user_username, "user".password AS user_password, "user".name AS user_name, "user".email AS user_email, "user".acti
ve AS user_active \nFROM "user" \nWHERE "user".username IS NULL \n LIMIT %(param_1)s'] [parameters: [{}]]                                                                                             
Aug  2 01:57:17 timesketch1 timesketch: 172.16.0.40 - - [02/Aug/2017 01:57:17] "GET /login/?next=%2F HTTP/1.1" 500 -   
```

**Comment by berggren** [comment]
Hi, thanks for reporting this. I have been unable to reproduce this issue. How are you running the server? Gunicorn(WSGI)+Nginx/apache as reverse proxy?

**Comment by bkvaluemeal** [comment]
Hey, sorry for the extremely long delay. Timesketch is running normally through the `tsctl` application and is served through a reverse proxy with nginx on another host. I've been able to mitigate the issue by patching [`timesketch/models/__init__.py`](https://github.com/google/timesketch/blob/master/timesketch/models/__init__.py#L43) with `engine = create_engine(url, pool_recycle=60, pool_reset_on_return='rollback')`. I'm not sure if this is the best way to tackle the problem, but it appears to reduce the burden on Postgres significantly.

**Comment by berggren** [comment]
Ok, you don't want to run the backend with the tsctl command. This will run
the application in developer mode and is not releasing DB sessions etc. You
want to run this via a proper WSGI server and then reverse proxy to that.
In our WSGI we have this that takes care of cleaning up DB sessions:

@application.teardown_appcontext
def shutdown_session(exception=None):
    """Remove the database session after every request or app shutdown."""
    db_session.remove()

For example, use gunicorn:
$ pip install gunicorn
$ gunicorn --workers 3 --bind 127.0.0.1:8000 timesketch.wsgi

See the official docs from gunicorn on how to run it in production:
http://docs.gunicorn.org/en/stable/deploy.html

/jbn

**Comment by bkvaluemeal** [comment]
This fixed the issue and I haven't noticed anything since. Thanks for your help!
