### ISSUE TITLE
Plaso Upload broken then using latest plaso release

### ISSUE THREAD

**Issue by pettai** [google/timesketch#402]
Hi,

(Note: That the wiki page (https://github.com/google/timesketch/wiki/UserGuidePlasoUpload) says use plaso from gift/dev) 
Timesketch "20170721" - Plaso Upload feature breaks with the latest plaso (pre)release "20170819".
Celary worker outputs: 
```
[...]
[2017-08-27 17:40:21,540: INFO/ForkPoolWorker-15] Index name: 33c64e75825a473cb18dd3b0fd39972f
[2017-08-27 17:40:21,540: INFO/ForkPoolWorker-15] Timeline name: testclient.sunet.se--no_vss
[2017-08-27 17:40:21,540: INFO/ForkPoolWorker-15] Flush interval: 1000
[2017-08-27 17:40:21,541: INFO/ForkPoolWorker-15] Document type: plaso_event
[2017-08-27 17:40:21,541: INFO/ForkPoolWorker-15] Owner of the timeline: pettai@sunet.se
[2017-08-27 17:40:21,543: ERROR/ForkPoolWorker-15] Task timesketch.lib.tasks.run_plaso[33c64e75825a473cb18dd3b0fd39972f] raised unexpected: TypeError("__init__() got an unexpected keyword argument 'profiling_directory'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 210, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 85, in run_plaso
    counter = frontend.ExportEvents(storage_reader, output_module)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 212, in ExportEvents
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 80, in _CreateEngine
TypeError: __init__() got an unexpected keyword argument 'profiling_directory'
```

**Comment by pettai** [comment]
Fixed by https://github.com/google/timesketch/pull/449 ?

**Comment by pettai** [comment]
yes seems so
