### ISSUE TITLE
Missing file create_graph.cql

### ISSUE THREAD

**Issue by maestretti** [google/timesketch#490]
Looks like a missing file. I am trying to build the front end in docker. 

```

root@7fbc762c99b0:/# tsctl runserver -h 0.0.0.0 -p 5000
Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 32, in <module>
    from timesketch import create_app
  File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 47, in <module>
    from timesketch.api.experimental.resources import WinLoginsResource
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/experimental/resources.py", line 23, in <module>
    from timesketch.lib.experimental.create_graph import create_graph
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/experimental/create_graph.py", line 18, in <module>
    with open(os.path.join(THIS_DIR, 'create_graph.cql')) as f:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/timesketch/lib/experimental/create_graph.cql'
```
 I do see a create_graph.py...

```
root@7fbc762c99b0:/# ls /usr/local/lib/python2.7/dist-packages/timesketch/lib/experimental/                
__init__.py  __init__.pyc  create_graph.py  create_graph.pyc  delete_graph.py  delete_graph.pyc  utils.py  utils.pyc  win_logins.py  win_logins.pyc  win_services.py  win_services.pyc
```

**Comment by berggren** [comment]
Ack, fix is in the works

**Comment by berggren** [comment]
Fix is in.
