### ISSUE TITLE
File upload exception on a fresh installed system

### ISSUE THREAD

**Issue by deralexxx** [google/timesketch#609]
I receved the following error on a fresh installed timesketch:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 971, in post
    message=form.errors[u'file'][0],
KeyError: u'file'
```

Did some testing and the root cause seems to be: 
```
UPLOAD_ENABLED = current_app.config[u'UPLOAD_ENABLED']
```
In /usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py

Which I guess had for historic reasons a check for upload enabled, however if I activate upload in the /etc/timesketch.conf I receive the error:

```
sudo tsctl runserver  -h 0.0.0.0 -p 5000
Upload is enabled, but Plaso is not installed.
```

So I would open up the discussion, would it:
a) make sense to remove the check for plaso installed but still have upload enabled
or
b) mention the plaso installation in the basic installation requirements

+ deactivate the upload form if upload is disabled by config.

**Comment by deralexxx** [comment]
Ok nevermind, seems already being fixed but not in the latest version that is installed via pip...
