### ISSUE TITLE
After import: Cannot do anything with the timeline (broken pipe)

### ISSUE THREAD

**Issue by DevStudent77495** [google/timesketch#648]
Hello,

i imported my plasodata with psort:
 psort.py -o timesketch /tmp/test/test38.plaso 

plaso - psort version 20180630

Storage file	: /tmp/test/test38.plaso
2018-07-02 18:20:26,491 [INFO] (MainProcess) PID:2102 <base> POST http://127.0.0.1:9200/c3238ac2c6744cc2a1e2380eaea44f18/plaso_event/_bulk [status:200 request:0.482s]
2018-07-02 18:20:26,725 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1814002158339000064 to a datetime object with error: date value out of range
2018-07-02 18:20:26,726 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1814058449468999936 to a datetime object with error: date value out of range
2018-07-02 18:20:26,729 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833001912975000064 to a datetime object with error: date value out of range
2018-07-02 18:20:26,729 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833001912975000064 to a datetime object with error: date value out of range
2018-07-02 18:20:26,730 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833001912975000064 to a datetime object with error: date value out of range
2018-07-02 18:20:26,730 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833001912975000064 to a datetime object with error: date value out of range
2018-07-02 18:20:26,730 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833001912975000064 to a datetime object with error: date value out of range
2018-07-02 18:20:26,732 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833029932912000000 to a datetime object with error: date value out of range
2018-07-02 18:20:26,733 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833029932912000000 to a datetime object with error: date value out of range
2018-07-02 18:20:26,787 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833029933340999936 to a datetime object with error: date value out of range
2018-07-02 18:20:26,788 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833029933340999936 to a datetime object with error: date value out of range
2018-07-02 18:20:26,789 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833029933340999936 to a datetime object with error: date value out of range
2018-07-02 18:20:26,789 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833029933340999936 to a datetime object with error: date value out of range
2018-07-02 18:20:26,790 [ERROR] (MainProcess) PID:2102 <timelib> Unable to copy 1833029933340999936 to a datetime object with error: date value out of range
2018-07-02 18:20:27,572 [INFO] (MainProcess) PID:2102 <base> POST http://127.0.0.1:9200/c3238ac2c6744cc2a1e2380eaea44f18/plaso_event/_bulk [status:200 request:0.459s]
Processing completed.

******************************** Export results ********************************
        Events processed : 3176038
     Events MACB grouped : 3121544
Duplicate events removed : 41302
         Events filtered : 0
  Events from time slice : 0

This seems to work fine. 
After that, i tried to "work" with the timeline:
when i hit explorer, http 500 (internal server error) comes up
when i import the plaso file from the webui: it startet work, but never finishes.
when i enter a query it starts run and never come back with a result.

the logfiles shows this repeatly:
Exception happened during processing of request from ('127.0.0.1', 51558)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

it seems that something is broken, a have no idea how to fix that. 
thanks for your support

**Comment by deralexxx** [comment]
Hey @DevStudent77495 can you paste the first few lines of /tmp/test/test38.plaso just to make sure there is no issue there?

Thx

**Comment by berggren** [comment]
Closing as the last response 1.5y ago.
