### ISSUE TITLE
Timesketch in Docker doesn't survive container deletion and recreation

### ISSUE THREAD

**Issue by andysnowball** [google/timesketch#665]
Hi there, I run Timesketch under Docker (with docker-compose), which works fantastically well. However, when I run "docker-compose down" followed by "docker-compose up -d", at least one of the timelines within a sketch becomes corrupt and not readable. The symptom is an "Internal Server Error" within the web interface and the following error in the container logs for the timesketch container:

```
[2018-10-02 15:10:28,921] ERROR in app: Exception on /api/v1/sketches/3/explore/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 622, in post
    enable_scroll=False)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/datastores/elastic.py", line 283, in search
    scroll=scroll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')
```
I'm using the bundled docker-compose.yml file and suspect this is due to data being stored within the container and not persisted using volumes. Any help with fixing this issue would be very much appreciated.

Best regards,

Andy.

**Comment by berggren** [comment]
sorry, this report got lost. The docker stuff has been refactored lately, but this issue is because when you do a docker-compose down action, the database is deleted as well, if you don't run it seperatly.

Please reopen if you still see issues with this.
