### ISSUE TITLE
Exception on clicking the timeline

### ISSUE THREAD

**Issue by hfakar** [google/timesketch#687]
When I upload a plaso file around 350 mb it loads and shows the timeline with 0 events. when I click on a timeline I can see this error on the server side:
```

[2018-10-19 07:11:45,723] ERROR in app: Exception on /api/v1/sketches/4/explore/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 641, in post
    enable_scroll=False)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/datastores/elastic.py", line 273, in search
    scroll=scroll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 655, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
NotFoundError: <unprintable NotFoundError object>
127.0.0.1 - - [19/Oct/2018 07:11:45] "POST /api/v1/sketches/4/explore/ HTTP/1.1" 500 -

```

**Comment by aguilajesus** [comment]
Hi @hfakar can you tell us a little more about your setup?
 - what version or commit of timesketch did you have at the time.
 - did you see any errors on celery logs?

**Comment by kiddinn** [comment]
is this still an issue?

the reporter has not replied since end of 2018, so I'm assuming this is no longer an issue, you can also upload the plaso file using the importer:


```
pip install timesketch-import-client
timesketch_importer.py --sketch_id <ID> <FILE>
```

closing this issue since I assume this has been fixed long time ago. if not, please open a new issue
