### ISSUE TITLE
Docker-Installation: Can not upload plaso file - Connection Error

### ISSUE THREAD

**Issue by fmurer** [google/timesketch#690]
I came over the following issue: After I finally could successfully install timesketch with docker (after dealing with the issues #688 and #664), I tried to upload a plaso file generated by log2timeline.

Unfortunately, I always get the following error:

```2018-10-26 06:39:25,336 [INFO] (MainProcess) PID:41 <timesketch_out> Timeline name: notebook-filtered
2018-10-26 06:39:25,337 [INFO] (MainProcess) PID:41 <timesketch_out> Owner of the timeline: admin
2018-10-26 06:39:25,340 [WARNING] (MainProcess) PID:41 <psort_tool> Appending to an already existing storage file.
2018-10-26 06:39:25,770 [WARNING] (MainProcess) PID:41 <knowledge_base> Unsupported time zone: PST, defaulting to UTC
2018-10-26 06:39:25,814 [WARNING] (MainProcess) PID:41 <base> HEAD http://elasticsearch:9200/2c27ffac281a4a67a1a77b085cfd37bf [status:N/A request:0.026s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elasticsearch5/connection/http_urllib3.py", line 135, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8869823250>: Failed to establish a new connection: [Errno 111] Connection refused
2018-10-26 06:39:25,871 [WARNING] (MainProcess) PID:41 <base> HEAD http://elasticsearch:9200/2c27ffac281a4a67a1a77b085cfd37bf [status:N/A request:0.018s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elasticsearch5/connection/http_urllib3.py", line 135, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8869823290>: Failed to establish a new connection: [Errno 111] Connection refused
2018-10-26 06:39:25,897 [WARNING] (MainProcess) PID:41 <base> HEAD http://elasticsearch:9200/2c27ffac281a4a67a1a77b085cfd37bf [status:N/A request:0.007s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elasticsearch5/connection/http_urllib3.py", line 135, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8869823210>: Failed to establish a new connection: [Errno 111] Connection refused
2018-10-26 06:39:25,919 [WARNING] (MainProcess) PID:41 <base> HEAD http://elasticsearch:9200/2c27ffac281a4a67a1a77b085cfd37bf [status:N/A request:0.020s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elasticsearch5/connection/http_urllib3.py", line 135, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8869823250>: Failed to establish a new connection: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 68, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 54, in Main
    tool.ProcessStorage()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/psort_tool.py", line 561, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 1011, in ExportEvents
    output_module.WriteHeader()
  File "/usr/lib/python2.7/dist-packages/plaso/output/timesketch_out.py", line 111, in WriteHeader
    self._CreateIndexIfNotExists(self._index_name, mappings)
  File "/usr/lib/python2.7/dist-packages/plaso/output/shared_elastic.py", line 328, in _CreateIndexIfNotExists
    exception))
RuntimeError: Unable to create Elasticsearch index with error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8869823250>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f8869823250>: Failed to establish a new connection: [Errno 111] Connection refused)```

Any suggestions there? Thank you

**Comment by fmurer** [comment]
Could be solved with help of this:
[https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html)

**Comment by aguilajesus** [comment]
Hi @fmurer I ran `docker-compose up` (adjusting the current issues with pyyaml and elasticsearch image) and it worked for me.

based on your comment it seems the timesketch container was not able to connect to the elasticsearch server `[Errno 111] Connection refused`. 

some things you could try:
- check if the container is running `docker container list`
- pull container logs from the elasticsearch and timesketch instance `docker container logs <container_name>`

**Comment by aguilajesus** [comment]
@fmurer were you able to solve this issue?

**Comment by fmurer** [comment]
I could solve the `Connection refused` issue by increasing the virutal memory.
```
sysctl -w vm.max_map_count=262144
```
see: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
