### ISSUE TITLE
DetachedInstanceError: instance is not bound to a Session; lazy load operation of attribute 'status' cannot proceed

### ISSUE THREAD

**Issue by aguilajesus** [google/timesketch#711]
## Setup method
   * docker-compose, fresh install.

## Trace
```[2018-11-16 01:13:18,248] ERROR in app: Exception on /api/v1/upload/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 1059, in post
    timeline, status_code=HTTP_STATUS_CODE_CREATED)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/api/v1/resources.py", line 260, in to_json
    schema[u'objects'] = [marshal(model, model_fields)]
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 648, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 647, in <genexpr>
    for k, v in fields.items())
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/fields.py", line 148, in output
    value = get_value(key if self.attribute is None else self.attribute, obj)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/fields.py", line 43, in get_value
    return _get_value_for_keys(key.split('.'), obj, default)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/fields.py", line 48, in _get_value_for_keys
    return _get_value_for_key(keys[0], obj, default)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/fields.py", line 60, in _get_value_for_key
    return getattr(obj, key, default)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
    (orm_util.state_str(state), self.key)
DetachedInstanceError: Parent instance <Timeline at 0x7fa9ae347f90> is not bound to a Session; lazy load operation of attribute 'status' cannot proceed```

**Comment by berggren** [comment]
Yeah, this is a bug. It only happens on the first load after the server have started. Looking into it.
