### ISSUE TITLE
EOFError when setting the password

### ISSUE THREAD

**Issue by fmurer** [google/timesketch#725]
I get the following error on `sudo docker-compose up`:

```
/usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Enter password: Traceback (most recent call last):
  File "/usr/local/bin/tsctl", line 600, in <module>
    shell_manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/bin/tsctl", line 85, in run
    password = self.get_password_from_prompt()
  File "/usr/local/bin/tsctl", line 74, in get_password_from_prompt
    first_password = prompt_pass(u'Enter password')
  File "/usr/local/lib/python2.7/dist-packages/flask_script/cli.py", line 35, in prompt_pass
    rv = getpass.getpass(prompt)
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
```
I specifically want to have set a random password every time

**Comment by aguilajesus** [comment]
Hi @fmurer can you send me the output of `docker container exec -it $(docker container list -f name=timesketch -q) env | grep TIMESKETCH`

the preferred method is to set these variables along with docker-compose, please check docker-compose documentation on [environment variables](https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers)

**Comment by aguilajesus** [comment]
a little bit more troubleshooting on setting the random password on the entrypoint [script](https://github.com/google/timesketch/blob/master/docker/docker-entrypoint.sh#L56)

since docker-compose set the variables to blank by default if they are not present, the script failed to pass the if condition (since it's looking for a variable not set) a minor fix on the if clause should solve the issue.

tested and work now `docker-compose up -d`
```
$ docker container logs $(docker container list -f name=timesketch -q)
TIMESKETCH_USER set to default: admin
TIMESKETCH_PASSWORD set randomly to: mXoapDJqTZ/S70dBtvthvubaVIw8lGhm9bsiS0zD6w4=
User admin created/updated
[2018-11-29 21:23:43 +0000] [32] [INFO] Starting gunicorn 19.7.1
[2018-11-29 21:23:43 +0000] [32] [INFO] Listening at: http://0.0.0.0:80 (32)
[2018-11-29 21:23:43 +0000] [32] [INFO] Using worker: sync
[2018-11-29 21:23:43 +0000] [39] [INFO] Booting worker with pid: 39
[2018-11-29 21:23:48,450: INFO/MainProcess] Connected to redis://redis:6379//
[2018-11-29 21:23:48,467: INFO/MainProcess] mingle: searching for neighbors
[2018-11-29 21:23:49,492: INFO/MainProcess] mingle: all alone
[2018-11-29 21:23:49,511: INFO/MainProcess] celery@ecdb3cc6e12e ready.
```

**Comment by kiddinn** [comment]
is this still an issue? there have been several changes to teh docker config lately

**Comment by berggren** [comment]
This has indeed been fixed. Closing this.
