### ISSUE TITLE
Erro when uploading a plaso or csv file

### ISSUE THREAD

**Issue by red-devilz** [google/timesketch#836]
I get the following error when I upload a csv file to 
[2019-02-19 04:47:55,060: ERROR/ForkPoolWorker-1] Task timesketch.lib.tasks.run_csv[d1a69fb4081148f199a0c4ed64ed781a] raised unexpected: RuntimeError(u"Missing fields in CSV header: [u'message', u'datetime', u'timestamp_desc']",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 210, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 119, in run_csv
    for event in read_and_validate_csv(source_file_path):
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/utils.py", line 59, in read_and_validate_csv
    u'Missing fields in CSV header: {0:s}'.format(missing_fields))
RuntimeError: Missing fields in CSV header: [u'message', u'datetime', u'timestamp_desc']

I also get the following error when uploading a .plaso file

[2019-02-19 05:38:53,973: INFO/MainProcess] Received task: timesketch.lib.tasks.run_plaso[dc1f2e06459f4fafa924dbb8966db4da]  
[2019-02-19 05:38:53,985: ERROR/ForkPoolWorker-1] Task timesketch.lib.tasks.run_plaso[dc1f2e06459f4fafa924dbb8966db4da] raised unexpected: NameError("global name 'psort' is not defined",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/__init__.py", line 210, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 71, in run_plaso
    frontend = psort.PsortFrontend()
NameError: global name 'psort' is not defined

**Comment by deralexxx** [comment]
can you share the file you tried to upload?

**Comment by berggren** [comment]
Hi, 

1) You seem to be missing some fields in your CSV. Can you share the header?
2) Do yo have Plaso installed on the server?

**Comment by kiddinn** [comment]
is this still an issue?

have you tried using the timesketch importer for the csv file?

```
pip install timesketch-import-client
timesketch_importer.py --sketch_id <ID> <FILE>
```

**Comment by kiddinn** [comment]
also not seen any replies to this issue since 2019, so Im closing this, this should work using these two methods:

1. plaso file upload by installing plaso on the server
2. CSV file by using the timesketch importer, which will check for missing fields
