### ISSUE TITLE
Csv export unicode error

### ISSUE THREAD

**Issue by dootyfree** [google/timesketch#891]
timesketch installed on sift workstation

error:  
[2019-05-15 21:15:23,166] ERROR in app: Exception on /sketch/8/explore/export/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/views/sketch.py", line 495, in export
    csv_writer.writerow(row)
  File "/usr/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 216: ordinal not in range(128)

**Comment by kiddinn** [comment]
Is this still an issue?

Can you share the CSV file you imported?

**Comment by kiddinn** [comment]
not heard anything in a long time, assuming this is no longer an issue, closing.

if this is still an issue, please re-open the issue.
