### ISSUE TITLE
psycopg2.OperationalError: SSL SYSCALL error: EOF detected after some day of psort running

### ISSUE THREAD

**Issue by garanews** [google/timesketch#904]
On May 28th launched psort.py with output timesketch, but after some day of computation I got this error:
```
Events:         Filtered        In time slice   Duplicates      MACB grouped    Total
                0               0               155879          143214956       144060172

Identifier              PID     Status          Memory          Events          Tags            Reports
Main                    8580    exporting       1.8 GiB         144060171 (0)   0 (0)           0 (0)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20190429', 'psort.py')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20190429-py3.6.egg/EGG-INFO/scripts/psort.py", line 68, in <module>
    if not Main():
  File "/usr/local/lib/python3.6/dist-packages/plaso-20190429-py3.6.egg/EGG-INFO/scripts/psort.py", line 54, in Main
    tool.ProcessStorage()
  File "/usr/local/lib/python3.6/dist-packages/plaso-20190429-py3.6.egg/plaso/cli/psort_tool.py", line 557, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20190429-py3.6.egg/plaso/multi_processing/psort.py", line 1018, in ExportEvents
    output_module.Close()
  File "/usr/local/lib/python3.6/dist-packages/plaso-20190429-py3.6.egg/plaso/output/timesketch_out.py", line 52, in Close
    index_name=self._index_name).first()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2979, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2771, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3106, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected
 [SQL: 'SELECT searchindex.id AS searchindex_id, searchindex.created_at AS searchindex_created_at, searchindex.updated_at AS searchindex_updated_at, searchindex.name AS searchindex_name, searchindex.description AS searchindex_description, searchindex.index_name AS searchindex_index_name, searchindex.user_id AS searchindex_user_id \nFROM searchindex \nWHERE searchindex.index_name = %(index_name_1)s \n LIMIT %(param_1)s'] [parameters: {'index_name_1': 'ced354b010f34cbaa28c581b80592e38', 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/e3q8)

```

If can helps, I see the entry in db:
```
timesketch=# select * from searchindex where id=9;
  9 | 2019-05-28 12:32:55.537219 | 2019-05-28 12:32:55.537219 | aaaa1| aaaa1| ced354b010f34cbaa28c581b80592e38 |
```

And in postgres log this:
``
sudo grep -r timesketch /var/log/postgresql/postgresql-11-main.log*
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:17:56.940 UTC [7145] timesketch@timesketch LOG:  could not receive data from client: Connection reset by peer
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:17:56.940 UTC [7145] timesketch@timesketch LOG:  unexpected EOF on client connection with an open transaction
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:24:10.126 UTC [548] timesketch@timesketch LOG:  could not receive data from client: Connection reset by peer
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:24:10.126 UTC [548] timesketch@timesketch LOG:  unexpected EOF on client connection with an open transaction
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:48:15.517 UTC [572] timesketch@timesketch LOG:  could not receive data from client: Connection reset by peer
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:48:15.517 UTC [572] timesketch@timesketch LOG:  unexpected EOF on client connection with an open transaction
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:48:48.457 UTC [667] timesketch@timesketch LOG:  could not receive data from client: Connection reset by peer
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:48:48.457 UTC [667] timesketch@timesketch LOG:  unexpected EOF on client connection with an open transaction
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:49:55.169 UTC [671] timesketch@timesketch LOG:  could not receive data from client: Connection reset by peer
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 10:49:55.169 UTC [671] timesketch@timesketch LOG:  unexpected EOF on client connection with an open transaction
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 13:02:50.732 UTC [676] timesketch@timesketch LOG:  could not receive data from client: Connection timed out
/var/log/postgresql/postgresql-11-main.log.1:2019-05-28 14:45:31.116 UTC [1060] timesketch@timesketch LOG:  could not receive data from client: Connection timed out
``

Can be something related to days to complete the psort?

**Comment by garanews** [comment]
I added manually an entry in timeline table referring the id in searchindex and I am able to see it. 
I added also an entry in  searchindex_status as ready and in timeline_status as ready, but in the UI I still see the timeline with "spinning circle" icon. 
Any idea to fix this?

**Comment by kiddinn** [comment]
@berggren can you help out with this?

**Comment by berggren** [comment]
@garanews I hope this is not still an issue. The timeline is pretty big (144M events) and I suspect that you might have hit some memory issues. 

I'll close this out if it is deemed too old and not relevant anymore.

Sorry that we missed this issue.

**Comment by berggren** [comment]
@garanews Please reopen if this is still causing problems for you.
