### ISSUE TITLE
Can't view data generated by Plaso versions later than 20180930 in Timesketch

### ISSUE THREAD

**Issue by andysnowball** [google/timesketch#908]
**Issue**
When attempting to view a timeline in Timesketch, any Plaso files generated by Plaso versions later than 20180930 fail to show and result in the following error being generated by Timesketch:

`[2019-06-10 13:32:45,674] ERROR in app: Exception on /api/v1/sketches/1/explore/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/timesketch/api/v1/resources.py", line 692, in post
    enable_scroll=enable_scroll)
  File "/usr/local/lib/python3.6/dist-packages/timesketch/lib/datastores/elastic.py", line 317, in search
    scroll=scroll_timeout)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'No mapping found for [datetime] in order to sort on')`

**Steps to reproduce**
1. Create a Plaso file using a version of log2timeline later than 20180930.
2. Start a new instance of Timesketch (current version on Github) in Docker.
3. Within the Timesketch Docker container, execute psort.py with output set to "timesketch" to import Plaso file.
4. Import will finish successfully, but attempting to view the timeline within Timesketch generates the above error.

I've checked this behavior and it is consistent when importing Plaso files from different systems. I have example working/non-working Plaso files if these would be useful.

**Comment by kiddinn** [comment]
This is in the ExploreResource in the API, while calling ES.
```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info) elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'No mapping found for [datetime] in order to sort on')
```

If you can share with me the plaso files you used, that would be helpful (those that caused the crash to occur)

**Comment by andysnowball** [comment]
Hi there,

Thanks very much for picking this issue up - much appreciated. I've uploaded an example Plaso file that exhibits the issue in the current release of Timesketch. The Plaso file was produced using log2timeline 20190708. Link to the Plaso file is here: https://cloud.snowyb.com/s/7cyB8Lt8oWzkEb9

Thanks again and best regards,

Andy.

**Comment by kiddinn** [comment]
sorry for the late response. I'm looking into this right now... 

I just uploaded your timeline and I'm still seeing the

```
elasticsearch.exceptions.RequestError: RequestError(400, ..... No mapping found for [datetime] in order to sort on')
```

I will take a closer look now.

**Comment by kiddinn** [comment]
according to pinfo this file should have 132.606 events imported...

I could run this file through psort without any hiccups on the TS instance, which should result in this file getting uploaded.

I was able to run psort on the file to generate a CSV file and import that... so this requires a bit more of a digging.

**Comment by kiddinn** [comment]
the issue may not lie within TS, it may be with plaso, so this issue could potentially be moved to plaso for further triage and fix of the TS output module.

**Comment by joachimmetz** [comment]
@kiddinn I assume this might be related to ES versions? the mappings keep changes between ES versions.

**Comment by joachimmetz** [comment]
@andysnowball I would recommend using latest both Plaso and Timesketch with ES 7 and let us know if the issue persists
