### ISSUE TITLE
Problem uploading csv file

### ISSUE THREAD

**Issue by nnyx7** [google/timesketch#930]
When trying to upload file in the timesketch celery crashed with the following message:
```
[2019-07-15 13:48:45,966: ERROR/ForkPoolWorker-7] Task timesketch.lib.tasks.run_csv_jsonl[84c8cfcc-2888-492e-9564-51b66489628b] raised unexpected: TypeError("'>=' not supported between instances of 'UnicodeDecodeError' and 'int'",)
Traceback (most recent call last):
  File "/usr/local/src/timesketch/timesketch/lib/tasks.py", line 467, in run_csv_jsonl
    for event in read_and_validate(source_file_path):
  File "/usr/local/src/timesketch/timesketch/lib/utils.py", line 63, in read_and_validate_csv
    csv_header = reader.fieldnames
  File "/usr/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 497: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/src/timesketch/timesketch/__init__.py", line 181, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/src/timesketch/timesketch/lib/tasks.py", line 478, in run_csv_jsonl
    error_msg = traceback.format_exc(e)
  File "/usr/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/usr/lib/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'UnicodeDecodeError' and 'int'
```

**Comment by deralexxx** [comment]
Seems your document that you try to upload contains chars that are not valid.
Any chance you can share the csv file?

**Comment by kiddinn** [comment]
can you also try to upload it usign the new importer?

```
pip install timesketch-import-client
timesketch_importer.py --sketch_id <ID> <FILE>
```

is tjhis still an issue?

**Comment by kiddinn** [comment]
not heard anything since last year, closing this one down since the importer should fix it. Please re-open if that's not the case
