### ISSUE TITLE
Error while uploading a csv file 

### ISSUE THREAD

**Issue by nagargourav** [google/timesketch#938]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/tasks.py", line 466, in run_csv_jsonl
    es.create_index(index_name=index_name, doc_type=event_type)
  File "/usr/local/lib/python2.7/dist-packages/timesketch/lib/datastores/elastic.py", line 487, in create_index
    if not self.client.indices.exists(index_name):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 224, in exists
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 123, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3772e0fa90>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3772e0fa90>: Failed to establish a new connection: [Errno 111] Connection refused)

**Comment by kiddinn** [comment]
how did you upload this CSV?

This is a connection error. Are you sure you were connected? If this is through the API client, the session may have expired, for instance.

**Comment by kiddinn** [comment]
not heard anything in a really long time, re-open it if it's still an issue.

you should also try to use the importer

```
pip install timesketch-import-client
timesketch_importer.py --sketch_id <ID> <FILE>
```
